/**
 * Device Metadata Catalog — Master dataset of metadata-driven device specifications.
 * Covers 24 Brands and all categories: Phones, Tablets, Laptops, Monitors, TVs, Wearables, Foldables, Custom.
 */

import type { CutoutSpec, SafeAreaSpec } from "../engine/DeviceEngine";

export type BezelStyle =
  | "titanium-natural"
  | "titanium-black"
  | "titanium-desert"
  | "armor-aluminum"
  | "glossy-stainless"
  | "matte-metal"
  | "thin-border"
  | "desktop-bezel";

export interface CompleteDeviceMetadata {
  id: string;
  brand: string;
  model: string;
  category: "phone" | "tablet" | "laptop" | "desktop" | "tv" | "wearable" | "foldable" | "custom";
  physicalWidthMm: number;
  physicalHeightMm: number;
  screenWidthPx: number;
  screenHeightPx: number;
  aspectRatio: number;
  resolutionLabel: string;
  safeArea: SafeAreaSpec;
  cornerRadiusPx: number;
  cutout: CutoutSpec;
  frameThicknessPx: number;
  bezelWidthPx: number;
  bezelStyle: BezelStyle;
  refreshRateHz: number;
  pixelDensityPpi: number;
  orientation: "portrait" | "landscape";
  supportedFeatures: string[];
}

export const DEVICE_METADATA_CATALOG: CompleteDeviceMetadata[] = [
  // ─── APPLE ────────────────────────────────────────────────────────────────
  {
    id: "apple-iphone-17-pro-max",
    brand: "Apple",
    model: "iPhone 17 Pro Max",
    category: "phone",
    physicalWidthMm: 77.6,
    physicalHeightMm: 163.0,
    screenWidthPx: 1320,
    screenHeightPx: 2868,
    aspectRatio: 1320 / 2868,
    resolutionLabel: "1320 x 2868 px",
    safeArea: { topPercent: 12, bottomPercent: 8, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 55,
    cutout: { type: "dynamic-island", widthPx: 120, heightPx: 35, topOffsetPx: 12 },
    frameThicknessPx: 14,
    bezelWidthPx: 6,
    bezelStyle: "titanium-natural",
    refreshRateHz: 120,
    pixelDensityPpi: 460,
    orientation: "portrait",
    supportedFeatures: ["dynamic-island", "pro-motion", "always-on", "hdr10", "action-button"],
  },
  {
    id: "apple-iphone-16-pro",
    brand: "Apple",
    model: "iPhone 16 Pro",
    category: "phone",
    physicalWidthMm: 71.5,
    physicalHeightMm: 149.6,
    screenWidthPx: 1206,
    screenHeightPx: 2622,
    aspectRatio: 1206 / 2622,
    resolutionLabel: "1206 x 2622 px",
    safeArea: { topPercent: 12, bottomPercent: 8, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 52,
    cutout: { type: "dynamic-island", widthPx: 115, heightPx: 34, topOffsetPx: 11 },
    frameThicknessPx: 12,
    bezelWidthPx: 7,
    bezelStyle: "titanium-black",
    refreshRateHz: 120,
    pixelDensityPpi: 460,
    orientation: "portrait",
    supportedFeatures: ["dynamic-island", "pro-motion", "always-on", "camera-control"],
  },
  {
    id: "apple-ipad-pro-13-m4",
    brand: "Apple",
    model: "iPad Pro 13\" (M4)",
    category: "tablet",
    physicalWidthMm: 215.5,
    physicalHeightMm: 281.6,
    screenWidthPx: 2064,
    screenHeightPx: 2752,
    aspectRatio: 2064 / 2752,
    resolutionLabel: "2064 x 2752 px",
    safeArea: { topPercent: 6, bottomPercent: 6, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 32,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 10,
    bezelWidthPx: 16,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 264,
    orientation: "portrait",
    supportedFeatures: ["tandem-oled", "pro-motion", "apple-pencil-pro"],
  },
  {
    id: "apple-watch-ultra-2",
    brand: "Apple",
    model: "Apple Watch Ultra 2",
    category: "wearable",
    physicalWidthMm: 44.0,
    physicalHeightMm: 49.0,
    screenWidthPx: 410,
    screenHeightPx: 502,
    aspectRatio: 410 / 502,
    resolutionLabel: "410 x 502 px",
    safeArea: { topPercent: 5, bottomPercent: 5, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 36,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 8,
    bezelWidthPx: 4,
    bezelStyle: "titanium-natural",
    refreshRateHz: 60,
    pixelDensityPpi: 338,
    orientation: "portrait",
    supportedFeatures: ["3000nits", "always-on"],
  },

  // ─── SAMSUNG ──────────────────────────────────────────────────────────────
  {
    id: "samsung-galaxy-s25-ultra",
    brand: "Samsung",
    model: "Galaxy S25 Ultra",
    category: "phone",
    physicalWidthMm: 77.6,
    physicalHeightMm: 162.8,
    screenWidthPx: 1440,
    screenHeightPx: 3120,
    aspectRatio: 1440 / 3120,
    resolutionLabel: "1440 x 3120 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 18,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 13,
    bezelWidthPx: 7,
    bezelStyle: "armor-aluminum",
    refreshRateHz: 120,
    pixelDensityPpi: 505,
    orientation: "portrait",
    supportedFeatures: ["s-pen", "vision-booster", "anti-reflective-glass", "amoled-2x"],
  },
  {
    id: "samsung-galaxy-z-fold-6",
    brand: "Samsung",
    model: "Galaxy Z Fold 6",
    category: "foldable",
    physicalWidthMm: 132.6,
    physicalHeightMm: 153.5,
    screenWidthPx: 1856,
    screenHeightPx: 2160,
    aspectRatio: 1856 / 2160,
    resolutionLabel: "1856 x 2160 px",
    safeArea: { topPercent: 6, bottomPercent: 6, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 24,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 14,
    bezelWidthPx: 10,
    bezelStyle: "armor-aluminum",
    refreshRateHz: 120,
    pixelDensityPpi: 374,
    orientation: "portrait",
    supportedFeatures: ["foldable-display", "under-display-camera", "s-pen-support"],
  },

  // ─── GOOGLE ───────────────────────────────────────────────────────────────
  {
    id: "google-pixel-9-pro-xl",
    brand: "Google",
    model: "Pixel 9 Pro XL",
    category: "phone",
    physicalWidthMm: 76.6,
    physicalHeightMm: 162.8,
    screenWidthPx: 1344,
    screenHeightPx: 2992,
    aspectRatio: 1344 / 2992,
    resolutionLabel: "1344 x 2992 px",
    safeArea: { topPercent: 11, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 48,
    cutout: { type: "punch-hole", widthPx: 24, heightPx: 24, topOffsetPx: 16 },
    frameThicknessPx: 13,
    bezelWidthPx: 8,
    bezelStyle: "glossy-stainless",
    refreshRateHz: 120,
    pixelDensityPpi: 486,
    orientation: "portrait",
    supportedFeatures: ["actua-display", "super-res-zoom", "tensor-g4"],
  },

  // ─── ONEPLUS / NOTHING / MOTOROLA ─────────────────────────────────────────
  {
    id: "oneplus-13",
    brand: "OnePlus",
    model: "OnePlus 13",
    category: "phone",
    physicalWidthMm: 76.5,
    physicalHeightMm: 162.9,
    screenWidthPx: 1440,
    screenHeightPx: 3168,
    aspectRatio: 1440 / 3168,
    resolutionLabel: "1440 x 3168 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 46,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 13,
    bezelWidthPx: 7,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 510,
    orientation: "portrait",
    supportedFeatures: ["hasselblad-camera", "displaymate-a+", "alert-slider"],
  },
  {
    id: "nothing-phone-2a-plus",
    brand: "Nothing",
    model: "Nothing Phone (2a) Plus",
    category: "phone",
    physicalWidthMm: 76.3,
    physicalHeightMm: 161.7,
    screenWidthPx: 1085,
    screenHeightPx: 2412,
    aspectRatio: 1085 / 2412,
    resolutionLabel: "1085 x 2412 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 40,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 12,
    bezelWidthPx: 7,
    bezelStyle: "thin-border",
    refreshRateHz: 120,
    pixelDensityPpi: 394,
    orientation: "portrait",
    supportedFeatures: ["glyph-interface", "transparent-back"],
  },
  {
    id: "motorola-edge-50-ultra",
    brand: "Motorola",
    model: "Motorola Edge 50 Ultra",
    category: "phone",
    physicalWidthMm: 72.4,
    physicalHeightMm: 161.1,
    screenWidthPx: 1220,
    screenHeightPx: 2712,
    aspectRatio: 1220 / 2712,
    resolutionLabel: "1220 x 2712 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 42,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 12,
    bezelWidthPx: 6,
    bezelStyle: "matte-metal",
    refreshRateHz: 144,
    pixelDensityPpi: 446,
    orientation: "portrait",
    supportedFeatures: ["curved-display", "pantone-validated", "real-wood-back"],
  },

  // ─── XIAOMI / REDMI / POCO / REALME ───────────────────────────────────────
  {
    id: "xiaomi-15-ultra",
    brand: "Xiaomi",
    model: "Xiaomi 15 Ultra",
    category: "phone",
    physicalWidthMm: 75.3,
    physicalHeightMm: 161.4,
    screenWidthPx: 1440,
    screenHeightPx: 3200,
    aspectRatio: 1440 / 3200,
    resolutionLabel: "1440 x 3200 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 42,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 14,
    bezelWidthPx: 7,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 522,
    orientation: "portrait",
    supportedFeatures: ["leica-optics", "dolby-vision", "3000-nits-peak"],
  },
  {
    id: "redmi-note-14-pro-plus",
    brand: "Redmi",
    model: "Redmi Note 14 Pro+",
    category: "phone",
    physicalWidthMm: 74.4,
    physicalHeightMm: 162.5,
    screenWidthPx: 1220,
    screenHeightPx: 2712,
    aspectRatio: 1220 / 2712,
    resolutionLabel: "1220 x 2712 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 40,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 12,
    bezelWidthPx: 7,
    bezelStyle: "thin-border",
    refreshRateHz: 120,
    pixelDensityPpi: 446,
    orientation: "portrait",
    supportedFeatures: ["curved-oled", "king-kong-architecture"],
  },
  {
    id: "poco-f6-pro",
    brand: "POCO",
    model: "POCO F6 Pro",
    category: "phone",
    physicalWidthMm: 74.9,
    physicalHeightMm: 160.9,
    screenWidthPx: 1440,
    screenHeightPx: 3200,
    aspectRatio: 1440 / 3200,
    resolutionLabel: "1440 x 3200 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 40,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 12,
    bezelWidthPx: 8,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 526,
    orientation: "portrait",
    supportedFeatures: ["flow-amoled", "4000nits-peak", "wildboost"],
  },
  {
    id: "realme-gt-7-pro",
    brand: "Realme",
    model: "Realme GT 7 Pro",
    category: "phone",
    physicalWidthMm: 76.9,
    physicalHeightMm: 162.5,
    screenWidthPx: 1264,
    screenHeightPx: 2780,
    aspectRatio: 1264 / 2780,
    resolutionLabel: "1264 x 2780 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 44,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 13,
    bezelWidthPx: 7,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 450,
    orientation: "portrait",
    supportedFeatures: ["realme-mars-design", "underwater-mode", "6000nits-peak"],
  },

  // ─── VIVO / IQOO / OPPO / HONOR / HUAWEI ──────────────────────────────────
  {
    id: "vivo-x200-pro",
    brand: "Vivo",
    model: "Vivo X200 Pro",
    category: "phone",
    physicalWidthMm: 75.9,
    physicalHeightMm: 162.4,
    screenWidthPx: 1260,
    screenHeightPx: 2800,
    aspectRatio: 1260 / 2800,
    resolutionLabel: "1260 x 2800 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 44,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 13,
    bezelWidthPx: 7,
    bezelStyle: "glossy-stainless",
    refreshRateHz: 120,
    pixelDensityPpi: 452,
    orientation: "portrait",
    supportedFeatures: ["zeiss-apo", "4500nits-peak", "arm-cortex-x925"],
  },
  {
    id: "iqoo-13",
    brand: "iQOO",
    model: "iQOO 13",
    category: "phone",
    physicalWidthMm: 76.7,
    physicalHeightMm: 163.4,
    screenWidthPx: 1440,
    screenHeightPx: 3200,
    aspectRatio: 1440 / 3200,
    resolutionLabel: "1440 x 3200 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 42,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 12,
    bezelWidthPx: 7,
    bezelStyle: "matte-metal",
    refreshRateHz: 144,
    pixelDensityPpi: 518,
    orientation: "portrait",
    supportedFeatures: ["monster-halo-light", "q2-gaming-chip", "2k-oled"],
  },
  {
    id: "oppo-find-x8-pro",
    brand: "OPPO",
    model: "OPPO Find X8 Pro",
    category: "phone",
    physicalWidthMm: 76.7,
    physicalHeightMm: 162.3,
    screenWidthPx: 1264,
    screenHeightPx: 2780,
    aspectRatio: 1264 / 2780,
    resolutionLabel: "1264 x 2780 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 44,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 13,
    bezelWidthPx: 7,
    bezelStyle: "glossy-stainless",
    refreshRateHz: 120,
    pixelDensityPpi: 450,
    orientation: "portrait",
    supportedFeatures: ["hasselblad-telephoto", "dual-periscope"],
  },
  {
    id: "honor-magic-7-pro",
    brand: "Honor",
    model: "Honor Magic 7 Pro",
    category: "phone",
    physicalWidthMm: 77.1,
    physicalHeightMm: 162.7,
    screenWidthPx: 1280,
    screenHeightPx: 2800,
    aspectRatio: 1280 / 2800,
    resolutionLabel: "1280 x 2800 px",
    safeArea: { topPercent: 11, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 44,
    cutout: { type: "dynamic-island", widthPx: 90, heightPx: 30, topOffsetPx: 12 },
    frameThicknessPx: 13,
    bezelWidthPx: 7,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 453,
    orientation: "portrait",
    supportedFeatures: ["3d-face-id", "oasis-eye-care"],
  },
  {
    id: "huawei-mate-70-pro",
    brand: "Huawei",
    model: "Huawei Mate 70 Pro",
    category: "phone",
    physicalWidthMm: 75.9,
    physicalHeightMm: 164.6,
    screenWidthPx: 1320,
    screenHeightPx: 2832,
    aspectRatio: 1320 / 2832,
    resolutionLabel: "1320 x 2832 px",
    safeArea: { topPercent: 12, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 42,
    cutout: { type: "notch", widthPx: 100, heightPx: 28, topOffsetPx: 10 },
    frameThicknessPx: 13,
    bezelWidthPx: 7,
    bezelStyle: "armor-aluminum",
    refreshRateHz: 120,
    pixelDensityPpi: 460,
    orientation: "portrait",
    supportedFeatures: ["kunlun-glass", "satellite-connectivity"],
  },

  // ─── SONY / ASUS / NOKIA / LENOVO ─────────────────────────────────────────
  {
    id: "sony-xperia-1-vi",
    brand: "Sony",
    model: "Sony Xperia 1 VI",
    category: "phone",
    physicalWidthMm: 74.0,
    physicalHeightMm: 162.0,
    screenWidthPx: 1080,
    screenHeightPx: 2340,
    aspectRatio: 1080 / 2340,
    resolutionLabel: "1080 x 2340 px",
    safeArea: { topPercent: 8, bottomPercent: 6, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 24,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 12,
    bezelWidthPx: 12,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 396,
    orientation: "portrait",
    supportedFeatures: ["bravia-core", "zeiss-t-star", "3.5mm-jack"],
  },
  {
    id: "asus-rog-phone-9-pro",
    brand: "Asus",
    model: "ASUS ROG Phone 9 Pro",
    category: "phone",
    physicalWidthMm: 77.0,
    physicalHeightMm: 163.8,
    screenWidthPx: 1080,
    screenHeightPx: 2400,
    aspectRatio: 1080 / 2400,
    resolutionLabel: "1080 x 2400 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 38,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 14,
    bezelWidthPx: 8,
    bezelStyle: "armor-aluminum",
    refreshRateHz: 185,
    pixelDensityPpi: 388,
    orientation: "portrait",
    supportedFeatures: ["ani-me-vision", "air-trigger", "185hz-display"],
  },
  {
    id: "nokia-x30-5g",
    brand: "Nokia",
    model: "Nokia X30 5G",
    category: "phone",
    physicalWidthMm: 73.9,
    physicalHeightMm: 158.9,
    screenWidthPx: 1080,
    screenHeightPx: 2400,
    aspectRatio: 1080 / 2400,
    resolutionLabel: "1080 x 2400 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 36,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 11,
    bezelWidthPx: 9,
    bezelStyle: "matte-metal",
    refreshRateHz: 90,
    pixelDensityPpi: 409,
    orientation: "portrait",
    supportedFeatures: ["recycled-aluminum", "pureview-camera"],
  },
  {
    id: "lenovo-legion-tab-y700",
    brand: "Lenovo",
    model: "Lenovo Legion Tab Y700",
    category: "tablet",
    physicalWidthMm: 129.5,
    physicalHeightMm: 208.5,
    screenWidthPx: 1600,
    screenHeightPx: 2560,
    aspectRatio: 1600 / 2560,
    resolutionLabel: "1600 x 2560 px",
    safeArea: { topPercent: 5, bottomPercent: 5, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 20,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 10,
    bezelWidthPx: 12,
    bezelStyle: "matte-metal",
    refreshRateHz: 144,
    pixelDensityPpi: 343,
    orientation: "portrait",
    supportedFeatures: ["144hz-gaming-tab", "dual-bypass-charging"],
  },

  // ─── TECNO / INFINIX / LAVA / MICROMAX / ITEL ─────────────────────────────
  {
    id: "tecno-phantom-v-fold-2",
    brand: "Tecno",
    model: "Tecno Phantom V Fold 2",
    category: "foldable",
    physicalWidthMm: 140.4,
    physicalHeightMm: 159.0,
    screenWidthPx: 2000,
    screenHeightPx: 2296,
    aspectRatio: 2000 / 2296,
    resolutionLabel: "2000 x 2296 px",
    safeArea: { topPercent: 6, bottomPercent: 6, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 26,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 13,
    bezelWidthPx: 9,
    bezelStyle: "matte-metal",
    refreshRateHz: 120,
    pixelDensityPpi: 388,
    orientation: "portrait",
    supportedFeatures: ["foldable-amoled", "aerospace-hinge"],
  },
  {
    id: "infinix-zero-flip",
    brand: "Infinix",
    model: "Infinix Zero Flip",
    category: "foldable",
    physicalWidthMm: 73.4,
    physicalHeightMm: 170.4,
    screenWidthPx: 1080,
    screenHeightPx: 2640,
    aspectRatio: 1080 / 2640,
    resolutionLabel: "1080 x 2640 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 38,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 12,
    bezelWidthPx: 8,
    bezelStyle: "glossy-stainless",
    refreshRateHz: 120,
    pixelDensityPpi: 413,
    orientation: "portrait",
    supportedFeatures: ["vlog-mode", "gopro-connectivity"],
  },
  {
    id: "lava-agni-3",
    brand: "Lava",
    model: "Lava Agni 3",
    category: "phone",
    physicalWidthMm: 76.0,
    physicalHeightMm: 163.7,
    screenWidthPx: 1200,
    screenHeightPx: 2652,
    aspectRatio: 1200 / 2652,
    resolutionLabel: "1200 x 2652 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 42,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 12,
    bezelWidthPx: 7,
    bezelStyle: "thin-border",
    refreshRateHz: 120,
    pixelDensityPpi: 429,
    orientation: "portrait",
    supportedFeatures: ["dual-amoled-display", "action-button-custom"],
  },
  {
    id: "micromax-in-note-2",
    brand: "Micromax",
    model: "Micromax IN Note 2",
    category: "phone",
    physicalWidthMm: 74.3,
    physicalHeightMm: 159.9,
    screenWidthPx: 1080,
    screenHeightPx: 2400,
    aspectRatio: 1080 / 2400,
    resolutionLabel: "1080 x 2400 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 36,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 11,
    bezelWidthPx: 9,
    bezelStyle: "thin-border",
    refreshRateHz: 60,
    pixelDensityPpi: 395,
    orientation: "portrait",
    supportedFeatures: ["amoled-display", "glass-finish"],
  },
  {
    id: "itel-s24",
    brand: "Itel",
    model: "Itel S24",
    category: "phone",
    physicalWidthMm: 76.0,
    physicalHeightMm: 163.5,
    screenWidthPx: 720,
    screenHeightPx: 1612,
    aspectRatio: 720 / 1612,
    resolutionLabel: "720 x 1612 px",
    safeArea: { topPercent: 10, bottomPercent: 7, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 34,
    cutout: { type: "punch-hole", widthPx: 22, heightPx: 22, topOffsetPx: 14 },
    frameThicknessPx: 11,
    bezelWidthPx: 10,
    bezelStyle: "thin-border",
    refreshRateHz: 90,
    pixelDensityPpi: 267,
    orientation: "portrait",
    supportedFeatures: ["color-changing-back", "108mp-camera"],
  },

  // ─── DESKTOP, LAPTOP, TV & CUSTOM ─────────────────────────────────────────
  {
    id: "desktop-monitor-4k",
    brand: "Generic",
    model: "4K UHD Studio Monitor",
    category: "desktop",
    physicalWidthMm: 600,
    physicalHeightMm: 340,
    screenWidthPx: 3840,
    screenHeightPx: 2160,
    aspectRatio: 3840 / 2160,
    resolutionLabel: "3840 x 2160 px",
    safeArea: { topPercent: 0, bottomPercent: 0, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 12,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 20,
    bezelWidthPx: 14,
    bezelStyle: "desktop-bezel",
    refreshRateHz: 144,
    pixelDensityPpi: 163,
    orientation: "landscape",
    supportedFeatures: ["hdr1000", "dci-p3", "thin-bezel"],
  },
  {
    id: "generic-smart-tv-55",
    brand: "Generic",
    model: "55\" 4K Smart TV",
    category: "tv",
    physicalWidthMm: 1210,
    physicalHeightMm: 680,
    screenWidthPx: 3840,
    screenHeightPx: 2160,
    aspectRatio: 3840 / 2160,
    resolutionLabel: "3840 x 2160 px",
    safeArea: { topPercent: 0, bottomPercent: 0, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 8,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 24,
    bezelWidthPx: 18,
    bezelStyle: "desktop-bezel",
    refreshRateHz: 120,
    pixelDensityPpi: 80,
    orientation: "landscape",
    supportedFeatures: ["oled-tv", "dolby-vision"],
  },
  {
    id: "custom-workspace-canvas",
    brand: "Custom",
    model: "Custom Dimensions Canvas",
    category: "custom",
    physicalWidthMm: 100,
    physicalHeightMm: 100,
    screenWidthPx: 1920,
    screenHeightPx: 1080,
    aspectRatio: 1920 / 1080,
    resolutionLabel: "Custom w x h px",
    safeArea: { topPercent: 0, bottomPercent: 0, leftPercent: 0, rightPercent: 0 },
    cornerRadiusPx: 0,
    cutout: { type: "none", widthPx: 0, heightPx: 0, topOffsetPx: 0 },
    frameThicknessPx: 0,
    bezelWidthPx: 0,
    bezelStyle: "thin-border",
    refreshRateHz: 60,
    pixelDensityPpi: 96,
    orientation: "landscape",
    supportedFeatures: ["custom-dimensions"],
  },
];

export function findCatalogDevice(id: string): CompleteDeviceMetadata | undefined {
  return DEVICE_METADATA_CATALOG.find((d) => d.id === id);
}
