export type SwatchRecipe = {
  id: string;
  name: string;
  category: string;
  categoryTag: string;
  volume: string;
  generatorId: string;
  palette: string[];
  mode: "light" | "dark" | "auto";
  seed: string;
  params: Record<string, unknown>;
  tags: string[];
  isNew?: boolean;
  isTrending?: boolean;
};

export type ArchiveCategory = {
  id: string;
  label: string;
  count: number;
};

export const ARCHIVE_PRESETS: SwatchRecipe[] = [
  // ─── 18 Generator Full Showcase Set ──────────────────────────────────────────
  {
    id: "mesh-prismatic",
    name: "Prismatic Mesh",
    category: "Mesh Gradient",
    categoryTag: "gradient",
    volume: "Vol. 10",
    generatorId: "mesh-gradient",
    palette: ["#1F3A5F", "#8A9A6E", "#D9541F", "#FAF7F0"],
    mode: "dark",
    seed: "mesh44",
    params: { pointsCount: 6, blurRadius: 0.6, pointSize: 0.9 },
    tags: ["gradient", "new", "trending"],
    isNew: true,
    isTrending: true,
  },
  {
    id: "aurora-boreal",
    name: "Boreal Horizon",
    category: "Aurora Flow",
    categoryTag: "gradient",
    volume: "Vol. 11",
    generatorId: "aurora-flow",
    palette: ["#0F172A", "#10B981", "#6366F1", "#EC4899"],
    mode: "dark",
    seed: "aurora88",
    params: { bandsCount: 6, curvature: 0.8, glowIntensity: 0.7 },
    tags: ["gradient", "new"],
    isNew: true,
  },
  {
    id: "bauhaus-construct",
    name: "Weimar Construct",
    category: "Bauhaus Blocks",
    categoryTag: "geometric",
    volume: "Vol. 12",
    generatorId: "bauhaus-blocks",
    palette: ["#FAF7F0", "#D9541F", "#1F3A5F", "#F59E0B"],
    mode: "light",
    seed: "bauhaus1919",
    params: { shapeCount: 20, gridSize: 5 },
    tags: ["geometric", "new"],
    isNew: true,
  },
  {
    id: "voronoi-cells",
    name: "Stained Glass Cells",
    category: "Voronoi Mosaic",
    categoryTag: "geometric",
    volume: "Vol. 13",
    generatorId: "voronoi-mosaic",
    palette: ["#111115", "#3B82F6", "#8B5CF6", "#EC4899"],
    mode: "dark",
    seed: "mosaic77",
    params: { cellCount: 40, borderThickness: 2 },
    tags: ["geometric"],
  },
  {
    id: "flow-vector",
    name: "Vector Drift Currents",
    category: "Flow Field",
    categoryTag: "generative",
    volume: "Vol. 14",
    generatorId: "flow-field",
    palette: ["#0F0D0B", "#10B981", "#06B6D4", "#F4F0E8"],
    mode: "dark",
    seed: "drift99",
    params: { particlesCount: 1200, noiseScale: 0.002, lineThickness: 1.5, stepCount: 60 },
    tags: ["generative", "trending"],
    isTrending: true,
  },
  {
    id: "topography-elevation",
    name: "Alpine Elevation Contour",
    category: "Topographic Lines",
    categoryTag: "minimal",
    volume: "Vol. 15",
    generatorId: "topographic-lines",
    palette: ["#FAF7F0", "#1C1A16", "#756E60", "#D9541F"],
    mode: "light",
    seed: "contour33",
    params: { contourCount: 24, lineThickness: 1.5, scale: 0.003 },
    tags: ["minimal", "new"],
    isNew: true,
  },
  {
    id: "marble-swirl",
    name: "Earthy Marble Veins",
    category: "Marble Fluid",
    categoryTag: "fluid",
    volume: "Vol. 16",
    generatorId: "marble-fluid",
    palette: ["#2A2A35", "#D6CCB5", "#8A9A6E", "#FAF7F0"],
    mode: "dark",
    seed: "marble55",
    params: { swirlIntensity: 1.5, veinContrast: 1.8, scale: 0.003 },
    tags: ["fluid"],
  },
  {
    id: "starfield-cosmic",
    name: "Orion Cosmic Dust",
    category: "Starfield Nebula",
    categoryTag: "dark",
    volume: "Vol. 17",
    generatorId: "starfield-nebula",
    palette: ["#0A0A0D", "#6366F1", "#A855F7", "#F43F5E"],
    mode: "dark",
    seed: "orion101",
    params: { starDensity: 500, nebulaGlow: 0.7, twinkleFactor: 0.8 },
    tags: ["dark", "new"],
    isNew: true,
  },
  {
    id: "lowpoly-peaks",
    name: "Crystalline Peaks",
    category: "Low-Poly Terrain",
    categoryTag: "geometric",
    volume: "Vol. 18",
    generatorId: "lowpoly-terrain",
    palette: ["#0F172A", "#38BDF8", "#818CF8", "#F8FAFC"],
    mode: "dark",
    seed: "peaks2024",
    params: { gridDensity: 14, displacement: 0.8 },
    tags: ["3d", "trending"],
    isTrending: true,
  },
  {
    id: "halftone-pop",
    name: "Pop Art Halftone",
    category: "Halftone Dots",
    categoryTag: "geometric",
    volume: "Vol. 19",
    generatorId: "halftone-dots",
    palette: ["#FAF7F0", "#E11D48", "#1E293B", "#F59E0B"],
    mode: "light",
    seed: "halftone66",
    params: { dotGridSize: 24, maxDotScale: 0.9 },
    tags: ["geometric"],
  },
  {
    id: "metaballs-lava",
    name: "Organic Lava Orbs",
    category: "Metaballs",
    categoryTag: "fluid",
    volume: "Vol. 20",
    generatorId: "metaballs",
    palette: ["#18171C", "#F97316", "#EF4444", "#FACC15"],
    mode: "dark",
    seed: "lava88",
    params: { blobCount: 8, threshold: 0.7, blobSize: 1.0 },
    tags: ["fluid", "new"],
    isNew: true,
  },
  {
    id: "wave-harmonic",
    name: "Harmonic Ripple Matrix",
    category: "Wave Interference",
    categoryTag: "waveform",
    volume: "Vol. 21",
    generatorId: "wave-interference",
    palette: ["#0D9488", "#14B8A6", "#CCFBF1", "#0F172A"],
    mode: "dark",
    seed: "ripple55",
    params: { waveSources: 3, frequency: 0.015, amplitude: 1.0 },
    tags: ["waveform"],
  },
  {
    id: "duotone-flare",
    name: "Solar Flare Burst",
    category: "Duotone Burst",
    categoryTag: "abstract",
    volume: "Vol. 22",
    generatorId: "duotone-burst",
    palette: ["#4C1D95", "#DDD6FE", "#7C3AED", "#1E1B4B"],
    mode: "dark",
    seed: "flare99",
    params: { raysCount: 24, raySharpness: 0.5, centerX: 0.5, centerY: 0.5 },
    tags: ["abstract"],
  },
  {
    id: "grain-analog",
    name: "Analog Film Texture",
    category: "Grain Texture",
    categoryTag: "minimal",
    volume: "Vol. 23",
    generatorId: "grain-texture",
    palette: ["#FAF7F0", "#4A453C", "#1C1A16", "#D9541F"],
    mode: "light",
    seed: "film35mm",
    params: { grainIntensity: 0.18, gradientAngle: 45 },
    tags: ["minimal"],
  },

  // ─── Botanicals (8 items) ──────────────────────────────────────────────────
  {
    id: "terracotta-bloom",
    name: "Terracotta Bloom",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#8A9A6E", "#E4DCC8", "#4B5A3E", "#2B2A26"],
    mode: "dark",
    seed: "bloom99",
    params: { layers: 6, jaggedness: 0.35, smoothing: 0.75, lineThickness: 2, amplitude: 0.65, fillBelow: true },
    tags: ["botanicals", "new"],
    isNew: true,
  },
  {
    id: "indigo-garden",
    name: "Indigo Garden",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 06",
    generatorId: "fluid-gradient",
    palette: ["#FAF8F4", "#1F3A5F", "#3E6E9E", "#101820"],
    mode: "dark",
    seed: "indigo77",
    params: { blobCount: 5, distortion: 0.4, swirl: 0.7, contrast: 1.2, saturation: 1.1 },
    tags: ["botanicals", "new"],
    isNew: true,
  },
  {
    id: "olive-branch",
    name: "Olive Branch",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 01",
    generatorId: "waveform",
    palette: ["#DAD4C4", "#8A9A72", "#5C6E4E", "#37402C"],
    mode: "light",
    seed: "olive05",
    params: { layers: 4, jaggedness: 0.25, smoothing: 0.85, lineThickness: 2.5, amplitude: 0.7, fillBelow: true },
    tags: ["botanicals"],
  },
  {
    id: "typography-cyberpunk",
    name: "Cyberpunk Type",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 07",
    generatorId: "typography",
    palette: ["#080711", "#240046", "#FF007F", "#00F0FF", "#FFE600"],
    mode: "dark",
    seed: "12m8twlk",
    params: { text: "WallMyDevice", font: "JetBrains Mono", size: 0.4, weight: 700, letterSpacing: 0, alignment: "center" },
    tags: ["typography", "trending"],
    isTrending: true,
  },
  {
    id: "forest-depth",
    name: "Forest Depth",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 08",
    generatorId: "fluid-gradient",
    palette: ["#1A2B1A", "#3A5E3A", "#7A9E72", "#DAD4C4"],
    mode: "dark",
    seed: "forest11",
    params: { blobCount: 6, distortion: 0.3, swirl: 0.5, contrast: 1.15, saturation: 0.85 },
    tags: ["botanicals"],
  },
  {
    id: "fern-shadow",
    name: "Fern Shadow",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 09",
    generatorId: "waveform",
    palette: ["#2C3B28", "#5C7A50", "#A8C490", "#EDE8DC"],
    mode: "dark",
    seed: "fern22",
    params: { layers: 8, jaggedness: 0.2, smoothing: 0.88, lineThickness: 1.5, amplitude: 0.55, fillBelow: true },
    tags: ["botanicals", "new"],
    isNew: true,
  },
  {
    id: "sage-smoke",
    name: "Sage Smoke",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 10",
    generatorId: "fluid-gradient",
    palette: ["#E2DDD4", "#A0A882", "#627058", "#2E3328"],
    mode: "light",
    seed: "sage33",
    params: { blobCount: 4, distortion: 0.45, swirl: 0.6, contrast: 1.05, saturation: 0.78 },
    tags: ["botanicals"],
  },
  {
    id: "moss-tide",
    name: "Moss Tide",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 11",
    generatorId: "geometric",
    palette: ["#38472E", "#637A52", "#9CB07E", "#F0EBDE"],
    mode: "dark",
    seed: "moss44",
    params: { shape: "circles", gridSize: 10, rotation: 0.25, strokeWidth: 1.2, density: 0.6, fillMode: "fill" },
    tags: ["botanicals"],
  },

  // ─── Geometric (7 items) ──────────────────────────────────────────────────
  {
    id: "arches-shadows",
    name: "Arches & Shadows",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#DAD4C4", "#6E7A5C", "#3E4A32", "#2B2A26"],
    mode: "light",
    seed: "arch33",
    params: { shape: "rects", gridSize: 10, rotation: 0.45, strokeWidth: 2, density: 0.65, fillMode: "both" },
    tags: ["geometric"],
  },
  {
    id: "cobalt-fracture",
    name: "Cobalt Fracture",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 01",
    generatorId: "geometric",
    palette: ["#101820", "#1F3A5F", "#3E6E9E", "#D4CDBC"],
    mode: "dark",
    seed: "cobalt88",
    params: { shape: "triangles", gridSize: 18, rotation: 0.3, strokeWidth: 1, density: 0.8, fillMode: "stroke" },
    tags: ["geometric", "trending"],
    isTrending: true,
  },
  {
    id: "grid-lattice",
    name: "Grid Lattice",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 03",
    generatorId: "geometric",
    palette: ["#F0EBE0", "#2B2A26", "#8A8579", "#C9552F"],
    mode: "light",
    seed: "lattice15",
    params: { shape: "rects", gridSize: 16, rotation: 0, strokeWidth: 1, density: 0.9, fillMode: "stroke" },
    tags: ["geometric", "new"],
    isNew: true,
  },
  {
    id: "hex-field",
    name: "Hex Field",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 04",
    generatorId: "geometric",
    palette: ["#181820", "#2A2A40", "#4A4A80", "#9090C0"],
    mode: "dark",
    seed: "hexfield",
    params: { shape: "circles", gridSize: 12, rotation: 0, strokeWidth: 1.5, density: 0.75, fillMode: "fill" },
    tags: ["geometric"],
  },
  {
    id: "diamond-grid",
    name: "Diamond Grid",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 05",
    generatorId: "geometric",
    palette: ["#FAF8F4", "#C9552F", "#2B2A26", "#E4DFD3"],
    mode: "light",
    seed: "diamond7",
    params: { shape: "rects", gridSize: 14, rotation: 0.45, strokeWidth: 1.8, density: 0.7, fillMode: "both" },
    tags: ["geometric", "trending"],
    isTrending: true,
  },
  {
    id: "circuit-lines",
    name: "Circuit Lines",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 06",
    generatorId: "geometric",
    palette: ["#0A1A0A", "#1A5C1A", "#2AA02A", "#7AE07A"],
    mode: "dark",
    seed: "circuit9",
    params: { shape: "rects", gridSize: 20, rotation: 0, strokeWidth: 0.8, density: 0.85, fillMode: "stroke" },
    tags: ["geometric"],
  },
  {
    id: "prism-break",
    name: "Prism Break",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 07",
    generatorId: "geometric",
    palette: ["#101025", "#302060", "#6040C0", "#C080FF"],
    mode: "dark",
    seed: "prism77",
    params: { shape: "triangles", gridSize: 16, rotation: 0.6, strokeWidth: 1.2, density: 0.72, fillMode: "fill" },
    tags: ["geometric", "new"],
    isNew: true,
  },

  // ─── Abstract (6 items) ───────────────────────────────────────────────────
  {
    id: "sagebrush-lines",
    name: "Sagebrush Lines",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 03",
    generatorId: "waveform",
    palette: ["#DAD4C4", "#8A9A72", "#5C6E4E", "#37402C"],
    mode: "light",
    seed: "sage88",
    params: { layers: 8, jaggedness: 0.15, smoothing: 0.9, lineThickness: 1.2, amplitude: 0.5, fillBelow: false },
    tags: ["abstract", "earth-sand"],
  },
  {
    id: "blush-terrain",
    name: "Blush Terrain",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#F3DDD1", "#C9552F", "#5A2411", "#FAF8F4"],
    mode: "light",
    seed: "blush12",
    params: { blobCount: 3, distortion: 0.7, swirl: 0.3, contrast: 0.95, saturation: 1.05 },
    tags: ["abstract", "new"],
    isNew: true,
  },
  {
    id: "aurora-wave",
    name: "Aurora Wave",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 08",
    generatorId: "waveform",
    palette: ["#0D1B2A", "#00B4D8", "#48CAE4", "#90E0EF"],
    mode: "dark",
    seed: "aurora12",
    params: { layers: 10, jaggedness: 0.2, smoothing: 0.92, lineThickness: 1.8, amplitude: 0.6, fillBelow: false },
    tags: ["abstract"],
  },
  {
    id: "oil-slick",
    name: "Oil Slick",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 09",
    generatorId: "fluid-gradient",
    palette: ["#1A1025", "#4A1055", "#8A3080", "#D880D8"],
    mode: "dark",
    seed: "oilslick",
    params: { blobCount: 5, distortion: 0.85, swirl: 0.7, contrast: 1.25, saturation: 1.3 },
    tags: ["abstract"],
  },
  {
    id: "static-noise",
    name: "Static Noise",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 10",
    generatorId: "waveform",
    palette: ["#1A1A1A", "#444444", "#888888", "#CCCCCC"],
    mode: "dark",
    seed: "static66",
    params: { layers: 12, jaggedness: 0.8, smoothing: 0.3, lineThickness: 0.8, amplitude: 0.4, fillBelow: false },
    tags: ["abstract", "monochrome"],
  },
  {
    id: "nebula-drift",
    name: "Nebula Drift",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 11",
    generatorId: "fluid-gradient",
    palette: ["#050510", "#1A0A30", "#3A1A60", "#8040C0"],
    mode: "dark",
    seed: "nebula33",
    params: { blobCount: 6, distortion: 0.6, swirl: 0.9, contrast: 1.4, saturation: 1.5 },
    tags: ["abstract", "dark"],
  },

  // ─── Monochrome (5 items) ─────────────────────────────────────────────────
  {
    id: "inkleaf",
    name: "Inkleaf",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 01",
    generatorId: "geometric",
    palette: ["#FAF8F4", "#5B584F", "#2B2A26", "#8A8579"],
    mode: "dark",
    seed: "inkleaf01",
    params: { shape: "circles", gridSize: 12, rotation: 0.15, strokeWidth: 1.5, density: 0.7, fillMode: "fill" },
    tags: ["monochrome", "trending"],
    isTrending: true,
  },
  {
    id: "monochrome-grid",
    name: "Monochrome Grid",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#09090b", "#27272a", "#a1a1aa", "#fafafa"],
    mode: "dark",
    seed: "monogrid",
    params: { shape: "rects", gridSize: 14, rotation: 0, strokeWidth: 1.2, density: 0.75, fillMode: "fill" },
    tags: ["monochrome"],
  },
  {
    id: "type-specimen",
    name: "Type Specimen",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 03",
    generatorId: "typography",
    palette: ["#FAF8F4", "#2B2A26", "#8A8579"],
    mode: "light",
    seed: "typespec",
    params: { text: "SWATCH", font: "Inter", size: 0.45, weight: 700, letterSpacing: 0.15, alignment: "center" },
    tags: ["monochrome", "new"],
    isNew: true,
  },
  {
    id: "graphite-flow",
    name: "Graphite Flow",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#1A1A1A", "#404040", "#808080", "#D0D0D0"],
    mode: "dark",
    seed: "graphite5",
    params: { layers: 9, jaggedness: 0.3, smoothing: 0.8, lineThickness: 1.5, amplitude: 0.6, fillBelow: true },
    tags: ["monochrome"],
  },
  {
    id: "ink-wash",
    name: "Ink Wash",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#FAFAFA", "#E0E0E0", "#A0A0A0", "#404040"],
    mode: "light",
    seed: "inkwash8",
    params: { blobCount: 4, distortion: 0.5, swirl: 0.4, contrast: 0.9, saturation: 0.0 },
    tags: ["monochrome"],
  },

  // ─── Earth & sand (5 items) ───────────────────────────────────────────────
  {
    id: "dune-flow",
    name: "Dune Flow",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#E4DCC8", "#C79A66", "#8A8579", "#2F4A5C"],
    mode: "light",
    seed: "dune42",
    params: { blobCount: 4, distortion: 0.6, swirl: 0.45, contrast: 1.1, saturation: 0.9 },
    tags: ["earth-sand", "trending"],
    isTrending: true,
  },
  {
    id: "horizon-weave",
    name: "Horizon Weave",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 03",
    generatorId: "waveform",
    palette: ["#E4DCC8", "#C79A66", "#4B5A6E", "#2F4A5C"],
    mode: "dark",
    seed: "horizon10",
    params: { layers: 7, jaggedness: 0.45, smoothing: 0.6, lineThickness: 1.8, amplitude: 0.55, fillBelow: true },
    tags: ["earth-sand", "trending"],
    isTrending: true,
  },
  {
    id: "desert-rift",
    name: "Desert Rift",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#C4A882", "#8C6E50", "#5A4030", "#2E2018"],
    mode: "dark",
    seed: "desert22",
    params: { layers: 6, jaggedness: 0.5, smoothing: 0.65, lineThickness: 2, amplitude: 0.75, fillBelow: true },
    tags: ["earth-sand"],
  },
  {
    id: "ochre-field",
    name: "Ochre Field",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#F0E4CC", "#D4A850", "#8A6832", "#3C2810"],
    mode: "light",
    seed: "ochre55",
    params: { blobCount: 4, distortion: 0.4, swirl: 0.35, contrast: 1.0, saturation: 0.95 },
    tags: ["earth-sand", "new"],
    isNew: true,
  },
  {
    id: "clay-plates",
    name: "Clay Plates",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 06",
    generatorId: "geometric",
    palette: ["#E8D5BE", "#C8A87A", "#8A6840", "#4A3018"],
    mode: "light",
    seed: "clay77",
    params: { shape: "rects", gridSize: 8, rotation: 0.05, strokeWidth: 2.5, density: 0.55, fillMode: "fill" },
    tags: ["earth-sand"],
  },

  // ─── Bold & graphic (5 items) ─────────────────────────────────────────────
  {
    id: "ember-field",
    name: "Ember Field",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#5A2411", "#C9552F", "#F0B27A", "#2B2A26"],
    mode: "dark",
    seed: "ember55",
    params: { blobCount: 4, distortion: 0.8, swirl: 0.6, contrast: 1.3, saturation: 1.2 },
    tags: ["bold-graphic", "new"],
    isNew: true,
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#1A0500", "#FF4400", "#FF9900", "#FFD700"],
    mode: "dark",
    seed: "solar44",
    params: { blobCount: 5, distortion: 0.9, swirl: 0.7, contrast: 1.5, saturation: 1.6 },
    tags: ["bold-graphic", "trending"],
    isTrending: true,
  },
  {
    id: "neon-grid",
    name: "Neon Grid",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 05",
    generatorId: "geometric",
    palette: ["#050510", "#FF0080", "#00FFCC", "#8800FF"],
    mode: "dark",
    seed: "neongrid",
    params: { shape: "rects", gridSize: 22, rotation: 0, strokeWidth: 0.8, density: 0.9, fillMode: "stroke" },
    tags: ["bold-graphic"],
  },
  {
    id: "acid-wash",
    name: "Acid Wash",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 06",
    generatorId: "fluid-gradient",
    palette: ["#00FF00", "#FFFF00", "#FF0000", "#0000FF"],
    mode: "dark",
    seed: "acid88",
    params: { blobCount: 6, distortion: 0.95, swirl: 0.8, contrast: 1.6, saturation: 2.0 },
    tags: ["bold-graphic", "new"],
    isNew: true,
  },
  {
    id: "blood-orange",
    name: "Blood Orange",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 07",
    generatorId: "waveform",
    palette: ["#1A0800", "#C83000", "#FF5520", "#FFCC00"],
    mode: "dark",
    seed: "orange99",
    params: { layers: 5, jaggedness: 0.6, smoothing: 0.5, lineThickness: 3, amplitude: 0.8, fillBelow: true },
    tags: ["bold-graphic"],
  },

  // ─── Minimal (5 items) ────────────────────────────────────────────────────
  {
    id: "paper-field",
    name: "Paper Field",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 01",
    generatorId: "waveform",
    palette: ["#F8F5F0", "#E8E0D5", "#C8BFB0", "#A09888"],
    mode: "light",
    seed: "paper11",
    params: { layers: 3, jaggedness: 0.1, smoothing: 0.95, lineThickness: 0.8, amplitude: 0.3, fillBelow: false },
    tags: ["minimal"],
  },
  {
    id: "linen-wave",
    name: "Linen Wave",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 02",
    generatorId: "waveform",
    palette: ["#EDE8E0", "#D8D0C4", "#C0B8A8", "#888070"],
    mode: "light",
    seed: "linen22",
    params: { layers: 4, jaggedness: 0.08, smoothing: 0.97, lineThickness: 1, amplitude: 0.25, fillBelow: false },
    tags: ["minimal", "new"],
    isNew: true,
  },
  {
    id: "dust-circle",
    name: "Dust Circle",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 03",
    generatorId: "geometric",
    palette: ["#F5F0E8", "#D0C8B8", "#A09888", "#706858"],
    mode: "light",
    seed: "dust33",
    params: { shape: "circles", gridSize: 6, rotation: 0, strokeWidth: 0.7, density: 0.7, fillMode: "stroke" },
    tags: ["minimal"],
  },
  {
    id: "fog-gradient",
    name: "Fog Gradient",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#FAFAF8", "#E8E8E5", "#D0D0CC", "#B0B0AC"],
    mode: "light",
    seed: "fog44",
    params: { blobCount: 3, distortion: 0.2, swirl: 0.15, contrast: 0.85, saturation: 0.1 },
    tags: ["minimal"],
  },
  {
    id: "rice-paper",
    name: "Rice Paper",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#F8F4EC", "#EDE4D4", "#D8CCC0", "#C0B4A8"],
    mode: "light",
    seed: "rice55",
    params: { blobCount: 2, distortion: 0.15, swirl: 0.1, contrast: 0.8, saturation: 0.05 },
    tags: ["minimal", "trending"],
    isTrending: true,
  },

  // ─── Gradient (5 items) ───────────────────────────────────────────────────
  {
    id: "sunset-pour",
    name: "Sunset Pour",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#FF6B35", "#F7C59F", "#EFEFD0", "#004E89"],
    mode: "light",
    seed: "sunset1",
    params: { blobCount: 4, distortion: 0.5, swirl: 0.55, contrast: 1.15, saturation: 1.2 },
    tags: ["gradient", "new"],
    isNew: true,
  },
  {
    id: "ocean-bloom",
    name: "Ocean Bloom",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#03045E", "#0077B6", "#00B4D8", "#90E0EF"],
    mode: "dark",
    seed: "ocean22",
    params: { blobCount: 5, distortion: 0.4, swirl: 0.65, contrast: 1.2, saturation: 1.1 },
    tags: ["gradient", "trending"],
    isTrending: true,
  },
  {
    id: "aurora-boreal",
    name: "Aurora Borealis",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#011627", "#00CFCF", "#00FF87", "#7B2FBE"],
    mode: "dark",
    seed: "aurora3",
    params: { blobCount: 6, distortion: 0.6, swirl: 0.8, contrast: 1.35, saturation: 1.4 },
    tags: ["gradient"],
  },
  {
    id: "candy-cloud",
    name: "Candy Cloud",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#FFE5F0", "#FFB3D1", "#FF80B5", "#FF4D9B"],
    mode: "light",
    seed: "candy44",
    params: { blobCount: 4, distortion: 0.35, swirl: 0.5, contrast: 1.0, saturation: 1.2 },
    tags: ["gradient", "pastel"],
  },
  {
    id: "violet-dusk",
    name: "Violet Dusk",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#1A0533", "#5C1A7A", "#A044C0", "#E8A0FF"],
    mode: "dark",
    seed: "violet5",
    params: { blobCount: 5, distortion: 0.55, swirl: 0.7, contrast: 1.3, saturation: 1.3 },
    tags: ["gradient"],
  },

  // ─── Typography (5 items) ─────────────────────────────────────────────────
  {
    id: "editorial-bold",
    name: "Editorial Bold",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 01",
    generatorId: "typography",
    palette: ["#101820", "#D4CDBC", "#C9552F", "#8A8579"],
    mode: "dark",
    seed: "editorial",
    params: { text: "TYPE", font: "Playfair Display", size: 0.25, weight: 900, letterSpacing: 0.05, alignment: "center" },
    tags: ["typography", "trending"],
    isTrending: true,
  },
  {
    id: "mono-whisper",
    name: "Mono Whisper",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 02",
    generatorId: "typography",
    palette: ["#FAF8F4", "#2B2A26", "#8A8579", "#C9552F"],
    mode: "light",
    seed: "whisper2",
    params: { text: "WALL", font: "Inter", size: 0.2, weight: 300, letterSpacing: 0.06, alignment: "center" },
    tags: ["typography", "minimal"],
  },
  {
    id: "serif-study",
    name: "Serif Study",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 03",
    generatorId: "typography",
    palette: ["#F5F0E8", "#1A1A18", "#6A6458", "#C9552F"],
    mode: "light",
    seed: "serif33",
    params: { text: "DESIGN", font: "Playfair Display", size: 0.18, weight: 700, letterSpacing: 0.04, alignment: "left" },
    tags: ["typography"],
  },
  {
    id: "code-poetic",
    name: "Code Poetic",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 04",
    generatorId: "typography",
    palette: ["#0A0F0A", "#00FF41", "#00AA2C", "#004D14"],
    mode: "dark",
    seed: "code44",
    params: { text: "01010101", font: "Inter", size: 0.15, weight: 700, letterSpacing: 0.04, alignment: "center" },
    tags: ["typography"],
  },
  {
    id: "blueprint-text",
    name: "Blueprint Text",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 05",
    generatorId: "typography",
    palette: ["#0A1A3A", "#1A4080", "#4080C0", "#C0E0FF"],
    mode: "dark",
    seed: "blueprint",
    params: { text: "STRUCTURE", font: "Inter", size: 0.16, weight: 400, letterSpacing: 0.04, alignment: "center" },
    tags: ["typography", "new"],
    isNew: true,
  },

  // ─── Retro (5 items) ──────────────────────────────────────────────────────
  {
    id: "vhs-noise",
    name: "VHS Noise",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 01",
    generatorId: "waveform",
    palette: ["#180020", "#600060", "#C000C0", "#FF80FF"],
    mode: "dark",
    seed: "vhs11",
    params: { layers: 12, jaggedness: 0.9, smoothing: 0.2, lineThickness: 0.6, amplitude: 0.35, fillBelow: false },
    tags: ["retro"],
  },
  {
    id: "vapor-grid",
    name: "Vapor Grid",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#0D0D2B", "#FF2D78", "#00FFFF", "#FF9A00"],
    mode: "dark",
    seed: "vapor22",
    params: { shape: "rects", gridSize: 18, rotation: 0.15, strokeWidth: 1, density: 0.8, fillMode: "stroke" },
    tags: ["retro", "trending"],
    isTrending: true,
  },
  {
    id: "lofi-sunset",
    name: "Lo-Fi Sunset",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#FFB347", "#FF6B6B", "#A855F7", "#6366F1"],
    mode: "light",
    seed: "lofi33",
    params: { blobCount: 4, distortion: 0.35, swirl: 0.4, contrast: 1.1, saturation: 0.9 },
    tags: ["retro", "new"],
    isNew: true,
  },
  {
    id: "pixel-garden",
    name: "Pixel Garden",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 04",
    generatorId: "geometric",
    palette: ["#AADDAA", "#448844", "#224422", "#88CC88"],
    mode: "light",
    seed: "pixel44",
    params: { shape: "rects", gridSize: 24, rotation: 0, strokeWidth: 0, density: 1, fillMode: "fill" },
    tags: ["retro"],
  },
  {
    id: "crt-glow",
    name: "CRT Glow",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 05",
    generatorId: "waveform",
    palette: ["#050505", "#003300", "#00AA00", "#00FF44"],
    mode: "dark",
    seed: "crt55",
    params: { layers: 8, jaggedness: 0.6, smoothing: 0.45, lineThickness: 1.2, amplitude: 0.5, fillBelow: false },
    tags: ["retro"],
  },

  // ─── Dark (5 items) ───────────────────────────────────────────────────────
  {
    id: "abyss",
    name: "Abyss",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#000000", "#0A0A0A", "#141414", "#1E1E1E"],
    mode: "dark",
    seed: "abyss11",
    params: { blobCount: 3, distortion: 0.7, swirl: 0.5, contrast: 1.0, saturation: 0.0 },
    tags: ["dark", "monochrome"],
  },
  {
    id: "void-matter",
    name: "Void Matter",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#050508", "#101018", "#202030", "#303050"],
    mode: "dark",
    seed: "void22",
    params: { shape: "circles", gridSize: 16, rotation: 0, strokeWidth: 0.5, density: 0.5, fillMode: "fill" },
    tags: ["dark"],
  },
  {
    id: "carbon-waves",
    name: "Carbon Waves",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 03",
    generatorId: "waveform",
    palette: ["#0A0A0A", "#1A1A1A", "#2A2A2A", "#3A3A3A"],
    mode: "dark",
    seed: "carbon3",
    params: { layers: 8, jaggedness: 0.25, smoothing: 0.85, lineThickness: 1.5, amplitude: 0.5, fillBelow: true },
    tags: ["dark"],
  },
  {
    id: "nightfall",
    name: "Nightfall",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#000010", "#050520", "#0A0A40", "#101060"],
    mode: "dark",
    seed: "night44",
    params: { blobCount: 4, distortion: 0.4, swirl: 0.6, contrast: 1.1, saturation: 0.8 },
    tags: ["dark", "new"],
    isNew: true,
  },
  {
    id: "obsidian-flow",
    name: "Obsidian Flow",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 05",
    generatorId: "waveform",
    palette: ["#020202", "#0D0D10", "#181820", "#252530"],
    mode: "dark",
    seed: "obsidian",
    params: { layers: 10, jaggedness: 0.3, smoothing: 0.9, lineThickness: 1, amplitude: 0.4, fillBelow: true },
    tags: ["dark", "minimal"],
  },

  // ─── Pastel (5 items) ─────────────────────────────────────────────────────
  {
    id: "cotton-sky",
    name: "Cotton Sky",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#E8F4FD", "#B3D9F5", "#8EC8F0", "#64B5E8"],
    mode: "light",
    seed: "cotton1",
    params: { blobCount: 4, distortion: 0.3, swirl: 0.4, contrast: 0.95, saturation: 0.7 },
    tags: ["pastel", "new"],
    isNew: true,
  },
  {
    id: "blush-petal",
    name: "Blush Petal",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#FFF0F0", "#FFD0D5", "#FFB0C0", "#FF90A8"],
    mode: "light",
    seed: "blush22",
    params: { blobCount: 4, distortion: 0.25, swirl: 0.35, contrast: 0.9, saturation: 0.75 },
    tags: ["pastel", "trending"],
    isTrending: true,
  },
  {
    id: "mint-cool",
    name: "Mint Cool",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#E8FFF5", "#B0EEDD", "#78DCC5", "#48C8A8"],
    mode: "light",
    seed: "mint33",
    params: { blobCount: 3, distortion: 0.3, swirl: 0.45, contrast: 0.92, saturation: 0.72 },
    tags: ["pastel"],
  },
  {
    id: "lavender-haze",
    name: "Lavender Haze",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#F5F0FF", "#DDD0F5", "#C0A8E8", "#A080D8"],
    mode: "light",
    seed: "lavender",
    params: { blobCount: 4, distortion: 0.28, swirl: 0.38, contrast: 0.88, saturation: 0.68 },
    tags: ["pastel"],
  },
  {
    id: "peach-soft",
    name: "Peach Soft",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 05",
    generatorId: "waveform",
    palette: ["#FFF5F0", "#FFD8C8", "#FFB898", "#FF9870"],
    mode: "light",
    seed: "peach55",
    params: { layers: 5, jaggedness: 0.12, smoothing: 0.92, lineThickness: 1.2, amplitude: 0.35, fillBelow: false },
    tags: ["pastel"],
  },

  // ─── Seasonal (5 items) ──────────────────────────────────────────────────
  {
    id: "winter-solstice",
    name: "Winter Solstice",
    category: "Seasonal",
    categoryTag: "seasonal",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#0B192C", "#1E3E62", "#000000", "#E6F4F1"],
    mode: "dark",
    seed: "solstice2026",
    params: { blobCount: 5, distortion: 0.35, swirl: 0.6, contrast: 1.25, saturation: 0.8 },
    tags: ["seasonal", "new", "dark"],
    isNew: true,
  },
  {
    id: "spring-thaw",
    name: "Spring Thaw",
    category: "Seasonal",
    categoryTag: "seasonal",
    volume: "Vol. 02",
    generatorId: "waveform",
    palette: ["#E8F5E9", "#A5D6A7", "#66BB6A", "#2E7D32"],
    mode: "light",
    seed: "springthaw",
    params: { layers: 5, jaggedness: 0.2, smoothing: 0.85, lineThickness: 2, amplitude: 0.5, fillBelow: true },
    tags: ["seasonal", "new"],
    isNew: true,
  },
  {
    id: "summer-haze",
    name: "Summer Haze",
    category: "Seasonal",
    categoryTag: "seasonal",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#FFF3E0", "#FFE0B2", "#FFB74D", "#FF9800"],
    mode: "light",
    seed: "summerhaze",
    params: { blobCount: 4, distortion: 0.45, swirl: 0.7, contrast: 1.1, saturation: 1.2 },
    tags: ["seasonal", "new"],
    isNew: true,
  },
  {
    id: "autumn-ember",
    name: "Autumn Ember",
    category: "Seasonal",
    categoryTag: "seasonal",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#210B00", "#5C1D00", "#A83E00", "#E06C00"],
    mode: "dark",
    seed: "autumnember",
    params: { layers: 6, jaggedness: 0.4, smoothing: 0.7, lineThickness: 1.8, amplitude: 0.6, fillBelow: true },
    tags: ["seasonal", "trending"],
    isTrending: true,
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    category: "Seasonal",
    categoryTag: "seasonal",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#FCE4EC", "#F8BBD0", "#F48FB1", "#EC407A"],
    mode: "light",
    seed: "sakura2026",
    params: { blobCount: 4, distortion: 0.25, swirl: 0.5, contrast: 1.0, saturation: 0.9 },
    tags: ["seasonal", "new"],
    isNew: true,
  },

  // ─── Cyberpunk & Tech (6 items) ──────────────────────────────────────────
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    category: "Cyberpunk",
    categoryTag: "cyberpunk",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#0A0A12", "#1F1B4E", "#FF007F", "#00F0FF"],
    mode: "dark",
    seed: "tokyo2077",
    params: { blobCount: 6, distortion: 0.5, swirl: 0.8, contrast: 1.4, saturation: 1.3 },
    tags: ["cyberpunk", "trending", "dark"],
    isTrending: true,
  },
  {
    id: "terminal-matrix",
    name: "Terminal Matrix",
    category: "Cyberpunk",
    categoryTag: "cyberpunk",
    volume: "Vol. 02",
    generatorId: "typography",
    palette: ["#050B05", "#0F2B0F", "#1A5C1A", "#00FF41"],
    mode: "dark",
    seed: "matrixcode",
    params: { text: "010101", font: "JetBrains Mono", size: 0.4, weight: 700, letterSpacing: 0.1, alignment: "center" },
    tags: ["cyberpunk", "new"],
    isNew: true,
  },
  {
    id: "synthwave-sunset",
    name: "Synthwave Sunset",
    category: "Cyberpunk",
    categoryTag: "cyberpunk",
    volume: "Vol. 03",
    generatorId: "geometric",
    palette: ["#15002A", "#4B0082", "#FF0055", "#FF9900"],
    mode: "dark",
    seed: "synth80s",
    params: { shape: "lines", gridSize: 12, rotation: 0.25, strokeWidth: 1.5, density: 0.8, fillMode: "stroke" },
    tags: ["cyberpunk", "trending"],
    isTrending: true,
  },
  {
    id: "glitch-matrix",
    name: "Glitch Matrix",
    category: "Cyberpunk",
    categoryTag: "cyberpunk",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#05050A", "#FF0055", "#00F0FF", "#E5E5E5"],
    mode: "dark",
    seed: "glitch2026",
    params: { layers: 8, jaggedness: 0.85, smoothing: 0.2, lineThickness: 1.5, amplitude: 0.8, fillBelow: false },
    tags: ["cyberpunk", "new"],
    isNew: true,
  },
  {
    id: "circuit-gold",
    name: "Circuit Gold",
    category: "Cyberpunk",
    categoryTag: "cyberpunk",
    volume: "Vol. 05",
    generatorId: "geometric",
    palette: ["#0D0E12", "#1D2026", "#D4AF37", "#FFDF00"],
    mode: "dark",
    seed: "circuitry",
    params: { shape: "circles", gridSize: 12, rotation: 0, strokeWidth: 1.5, density: 0.7, fillMode: "fill" },
    tags: ["cyberpunk"],
  },
  {
    id: "neon-pulse",
    name: "Neon Pulse",
    category: "Cyberpunk",
    categoryTag: "cyberpunk",
    volume: "Vol. 06",
    generatorId: "fluid-gradient",
    palette: ["#050014", "#3D0066", "#9900FF", "#00FFFF"],
    mode: "dark",
    seed: "neonpulse",
    params: { blobCount: 5, distortion: 0.6, swirl: 0.9, contrast: 1.35, saturation: 1.4 },
    tags: ["cyberpunk", "new"],
    isNew: true,
  },

  // ─── Cinematic & Film (6 items) ──────────────────────────────────────────
  {
    id: "cinestill-800",
    name: "CineStill 800T",
    category: "Cinematic",
    categoryTag: "cinematic",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#08121E", "#162B40", "#4A83A6", "#FF3300"],
    mode: "dark",
    seed: "cinestill800",
    params: { blobCount: 4, distortion: 0.35, swirl: 0.5, contrast: 1.2, saturation: 1.15 },
    tags: ["cinematic", "trending", "dark"],
    isTrending: true,
  },
  {
    id: "golden-hour-film",
    name: "Golden Hour Film",
    category: "Cinematic",
    categoryTag: "cinematic",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#2C1A0E", "#6B3E19", "#C47B2B", "#F5D089"],
    mode: "dark",
    seed: "goldenhour",
    params: { blobCount: 4, distortion: 0.3, swirl: 0.45, contrast: 1.1, saturation: 1.05 },
    tags: ["cinematic", "new"],
    isNew: true,
  },
  {
    id: "a24-mood",
    name: "A24 Atmospheric",
    category: "Cinematic",
    categoryTag: "cinematic",
    volume: "Vol. 03",
    generatorId: "waveform",
    palette: ["#0A0F0D", "#1A2E26", "#3B5C4F", "#8CA89B"],
    mode: "dark",
    seed: "a24mood",
    params: { layers: 5, jaggedness: 0.3, smoothing: 0.8, lineThickness: 1.5, amplitude: 0.5, fillBelow: true },
    tags: ["cinematic", "new"],
    isNew: true,
  },
  {
    id: "film-noir",
    name: "Film Noir",
    category: "Cinematic",
    categoryTag: "cinematic",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#000000", "#1C1C1C", "#404040", "#A0A0A0"],
    mode: "dark",
    seed: "filmnoir",
    params: { layers: 7, jaggedness: 0.5, smoothing: 0.6, lineThickness: 2, amplitude: 0.65, fillBelow: true },
    tags: ["cinematic", "dark"],
  },
  {
    id: "faded-polaroid",
    name: "Faded Polaroid",
    category: "Cinematic",
    categoryTag: "cinematic",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#FAF5EF", "#E6D7C3", "#C5B097", "#9E8A72"],
    mode: "light",
    seed: "polaroid70",
    params: { blobCount: 3, distortion: 0.2, swirl: 0.3, contrast: 0.95, saturation: 0.65 },
    tags: ["cinematic"],
  },
  {
    id: "blade-runner-orange",
    name: "Blade Runner Sunset",
    category: "Cinematic",
    categoryTag: "cinematic",
    volume: "Vol. 06",
    generatorId: "fluid-gradient",
    palette: ["#120500", "#471500", "#9E3200", "#FF6200"],
    mode: "dark",
    seed: "bladerunner2049",
    params: { blobCount: 5, distortion: 0.4, swirl: 0.65, contrast: 1.3, saturation: 1.25 },
    tags: ["cinematic", "new", "dark"],
    isNew: true,
  },

  // ─── Brutalism & Swiss (5 items) ──────────────────────────────────────────
  {
    id: "bauhaus-grid",
    name: "Bauhaus Primary",
    category: "Brutalism",
    categoryTag: "brutalism",
    volume: "Vol. 01",
    generatorId: "geometric",
    palette: ["#0A0A0A", "#E63946", "#FFB703", "#1D3557"],
    mode: "light",
    seed: "bauhaus1919",
    params: { shape: "rects", gridSize: 8, rotation: 0, strokeWidth: 2, density: 0.9, fillMode: "fill" },
    tags: ["brutalism", "trending"],
    isTrending: true,
  },
  {
    id: "swiss-typographic",
    name: "Swiss International",
    category: "Brutalism",
    categoryTag: "brutalism",
    volume: "Vol. 02",
    generatorId: "typography",
    palette: ["#F4F4F0", "#111111", "#E63946", "#555555"],
    mode: "light",
    seed: "swissstyle",
    params: { text: "HELVETICA", font: "Inter", size: 0.45, weight: 800, letterSpacing: -0.05, alignment: "center" },
    tags: ["brutalism", "new"],
    isNew: true,
  },
  {
    id: "anti-design-grid",
    name: "Anti-Design Yellow",
    category: "Brutalism",
    categoryTag: "brutalism",
    volume: "Vol. 03",
    generatorId: "geometric",
    palette: ["#FFEE00", "#000000", "#FF0055", "#0000FF"],
    mode: "light",
    seed: "antidesign",
    params: { shape: "triangles", gridSize: 10, rotation: 0.15, strokeWidth: 1.5, density: 0.8, fillMode: "fill" },
    tags: ["brutalism"],
  },
  {
    id: "blueprint-cyan",
    name: "Architectural Blueprint",
    category: "Brutalism",
    categoryTag: "brutalism",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#002B49", "#005587", "#0088CC", "#FFFFFF"],
    mode: "dark",
    seed: "blueprint2026",
    params: { layers: 10, jaggedness: 0.1, smoothing: 0.95, lineThickness: 1, amplitude: 0.5, fillBelow: false },
    tags: ["brutalism", "new"],
    isNew: true,
  },
  {
    id: "utility-warning",
    name: "Utility Hazard",
    category: "Brutalism",
    categoryTag: "brutalism",
    volume: "Vol. 05",
    generatorId: "typography",
    palette: ["#111111", "#FFD700", "#222222", "#FFFFFF"],
    mode: "dark",
    seed: "hazardstripes",
    params: { text: "CAUTION", font: "JetBrains Mono", size: 0.38, weight: 700, letterSpacing: 0.1, alignment: "center" },
    tags: ["brutalism"],
  },

  // ─── Ethereal & Neon Minimal (5 items) ─────────────────────────────────────
  {
    id: "holographic-mesh",
    name: "Holographic Foil",
    category: "Ethereal",
    categoryTag: "ethereal",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#F0F8FF", "#B0E0E6", "#FFB6C1", "#E6E6FA"],
    mode: "light",
    seed: "holo foil",
    params: { blobCount: 5, distortion: 0.5, swirl: 0.75, contrast: 1.05, saturation: 1.1 },
    tags: ["ethereal", "trending", "new"],
    isNew: true,
    isTrending: true,
  },
  {
    id: "frosted-glass-pastels",
    name: "Frosted Glass",
    category: "Ethereal",
    categoryTag: "ethereal",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#FAF0E6", "#E6E6FA", "#FFF0F5", "#F0FFF0"],
    mode: "light",
    seed: "frostedglass",
    params: { blobCount: 4, distortion: 0.2, swirl: 0.35, contrast: 0.9, saturation: 0.6 },
    tags: ["ethereal", "new"],
    isNew: true,
  },
  {
    id: "liquid-chrome",
    name: "Liquid Chrome",
    category: "Ethereal",
    categoryTag: "ethereal",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#0A0A0F", "#2A2A35", "#707085", "#D5D5E5"],
    mode: "dark",
    seed: "liquidchrome",
    params: { blobCount: 6, distortion: 0.6, swirl: 0.85, contrast: 1.45, saturation: 0.5 },
    tags: ["ethereal", "dark", "new"],
    isNew: true,
  },
  {
    id: "pearlescent-glow",
    name: "Pearlescent Glow",
    category: "Ethereal",
    categoryTag: "ethereal",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#FFFFFF", "#F5E6E8", "#D5E5E5", "#E5D5E5"],
    mode: "light",
    seed: "pearlescent",
    params: { blobCount: 4, distortion: 0.3, swirl: 0.4, contrast: 0.92, saturation: 0.75 },
    tags: ["ethereal"],
  },
  {
    id: "ghost-signal",
    name: "Ghost Signal",
    category: "Ethereal",
    categoryTag: "ethereal",
    volume: "Vol. 05",
    generatorId: "waveform",
    palette: ["#08080C", "#141420", "#28283E", "#00FFCC"],
    mode: "dark",
    seed: "ghostsignal",
    params: { layers: 6, jaggedness: 0.25, smoothing: 0.9, lineThickness: 1.2, amplitude: 0.45, fillBelow: false },
    tags: ["ethereal", "dark"],
  },

  // ─── Generative & Organic Fluids (Variety Expansion) ─────────────────────
  {
    id: "lava-lamp-melt",
    name: "Lava Lamp Melt",
    category: "Generative",
    categoryTag: "generative",
    volume: "Vol. 01",
    generatorId: "metaballs",
    palette: ["#1A0500", "#FF4400", "#FF9900", "#FFD700"],
    mode: "dark",
    seed: "lavalamp99",
    params: { blobCount: 7, threshold: 0.65, blobSize: 1.1 },
    tags: ["generative", "trending", "new"],
    isNew: true,
    isTrending: true,
  },
  {
    id: "quantum-fluid",
    name: "Quantum Spheres",
    category: "Generative",
    categoryTag: "generative",
    volume: "Vol. 02",
    generatorId: "metaballs",
    palette: ["#0B0C10", "#1F2833", "#66FCF1", "#45A29E"],
    mode: "dark",
    seed: "quantum88",
    params: { blobCount: 5, threshold: 0.7, blobSize: 0.9 },
    tags: ["generative", "new"],
    isNew: true,
  },
  {
    id: "andromeda-core",
    name: "Andromeda Nebula",
    category: "Cosmic",
    categoryTag: "cosmic",
    volume: "Vol. 01",
    generatorId: "starfield-nebula",
    palette: ["#03020C", "#180B30", "#5C1D8D", "#C84B9C", "#FF9E9E"],
    mode: "dark",
    seed: "andromeda2026",
    params: { starDensity: 450, nebulaGlow: 0.8, twinkleFactor: 0.7 },
    tags: ["cosmic", "dark", "trending"],
    isTrending: true,
  },
  {
    id: "deep-starlight",
    name: "Deep Starlight",
    category: "Cosmic",
    categoryTag: "cosmic",
    volume: "Vol. 02",
    generatorId: "starfield-nebula",
    palette: ["#02040A", "#081020", "#102845", "#4080C0"],
    mode: "dark",
    seed: "starlight11",
    params: { starDensity: 600, nebulaGlow: 0.5, twinkleFactor: 0.9 },
    tags: ["cosmic", "dark"],
  },
  {
    id: "volcanic-ridge",
    name: "Volcanic Terrain",
    category: "Landscape",
    categoryTag: "landscape",
    volume: "Vol. 01",
    generatorId: "lowpoly-terrain",
    palette: ["#120806", "#3A1810", "#8A3018", "#E86028", "#FFB040"],
    mode: "dark",
    seed: "volcano77",
    params: { gridDensity: 16, displacement: 0.85 },
    tags: ["landscape", "new"],
    isNew: true,
  },
  {
    id: "glacial-peaks",
    name: "Glacial Valleys",
    category: "Landscape",
    categoryTag: "landscape",
    volume: "Vol. 02",
    generatorId: "lowpoly-terrain",
    palette: ["#0A121A", "#1A3048", "#407098", "#90C0E0", "#E8F4FC"],
    mode: "dark",
    seed: "glacial44",
    params: { gridDensity: 18, displacement: 0.7 },
    tags: ["landscape", "trending"],
    isTrending: true,
  },
  {
    id: "newspaper-halftone",
    name: "Vintage Halftone",
    category: "Print",
    categoryTag: "print",
    volume: "Vol. 01",
    generatorId: "halftone-dots",
    palette: ["#FAF8F4", "#2B2A26", "#8A8579"],
    mode: "light",
    seed: "halftone55",
    params: { dotGridSize: 22, maxDotScale: 0.85 },
    tags: ["print", "minimal"],
  },
  {
    id: "pop-art-dots",
    name: "Pop Art Halftone",
    category: "Print",
    categoryTag: "print",
    volume: "Vol. 02",
    generatorId: "halftone-dots",
    palette: ["#FFEE00", "#FF0055", "#00F0FF", "#111111"],
    mode: "light",
    seed: "popart88",
    params: { dotGridSize: 18, maxDotScale: 0.9 },
    tags: ["print", "trending", "new"],
    isNew: true,
    isTrending: true,
  },
  {
    id: "moire-ripple",
    name: "Resonance Waves",
    category: "Generative",
    categoryTag: "generative",
    volume: "Vol. 03",
    generatorId: "wave-interference",
    palette: ["#0A0A12", "#1E1B4B", "#6366F1", "#A5B4FC"],
    mode: "dark",
    seed: "moire101",
    params: { waveSources: 4, frequency: 0.018, amplitude: 1.1 },
    tags: ["generative", "new"],
    isNew: true,
  },
  {
    id: "radial-sunburst",
    name: "Duotone Sunburst",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 08",
    generatorId: "duotone-burst",
    palette: ["#0F172A", "#F59E0B", "#EF4444"],
    mode: "dark",
    seed: "sunburst77",
    params: { raysCount: 30, raySharpness: 0.7, centerX: 0.5, centerY: 0.5 },
    tags: ["bold-graphic", "trending"],
    isTrending: true,
  },
  {
    id: "linen-grain-overlay",
    name: "Coarse Silk Grain",
    category: "Print",
    categoryTag: "print",
    volume: "Vol. 03",
    generatorId: "grain-texture",
    palette: ["#F4EFEA", "#D8CEBE", "#A09480", "#2C2822"],
    mode: "light",
    seed: "silkgrain33",
    params: { grainIntensity: 0.16, gradientAngle: 45 },
    tags: ["print", "minimal"],
  },
  {
    id: "aurora-curtain",
    name: "Boreal Ribbon",
    category: "Ethereal",
    categoryTag: "ethereal",
    volume: "Vol. 06",
    generatorId: "aurora-flow",
    palette: ["#050E1A", "#00D2A0", "#0078FF", "#A000FF"],
    mode: "dark",
    seed: "borealribbon",
    params: { bandsCount: 6, curvature: 0.8, glowIntensity: 0.85 },
    tags: ["ethereal", "dark", "trending"],
    isTrending: true,
  },
  {
    id: "constructivist-grid",
    name: "Constructivist Quad",
    category: "Brutalism",
    categoryTag: "brutalism",
    volume: "Vol. 06",
    generatorId: "bauhaus-blocks",
    palette: ["#1A1A1A", "#D9381E", "#E6A100", "#2B547E", "#F4F4F0"],
    mode: "light",
    seed: "quad1923",
    params: { shapeCount: 22, gridSize: 5 },
    tags: ["brutalism", "new"],
    isNew: true,
  },
  {
    id: "stained-voronoi",
    name: "Stained Glass Mosaic",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 08",
    generatorId: "voronoi-mosaic",
    palette: ["#0A0A10", "#8B008B", "#4169E1", "#00CED1", "#FFD700"],
    mode: "dark",
    seed: "stainedglass99",
    params: { cellCount: 42, borderThickness: 2.5 },
    tags: ["geometric", "trending"],
    isTrending: true,
  },
  {
    id: "magnetic-particles",
    name: "Magnetic Flow Field",
    category: "Generative",
    categoryTag: "generative",
    volume: "Vol. 04",
    generatorId: "flow-field",
    palette: ["#070A0F", "#1A2E40", "#3A78A0", "#70C0E0", "#F0F8FF"],
    mode: "dark",
    seed: "magneticflow",
    params: { particlesCount: 1400, noiseScale: 0.0018, lineThickness: 1.5, stepCount: 65 },
    tags: ["generative", "new"],
    isNew: true,
  },
  {
    id: "topography-elevation",
    name: "Alpine Topo Map",
    category: "Landscape",
    categoryTag: "landscape",
    volume: "Vol. 03",
    generatorId: "topographic-lines",
    palette: ["#FAF8F4", "#2B2A26", "#8A8579", "#C9552F"],
    mode: "light",
    seed: "alpinetopo12",
    params: { contourCount: 26, lineThickness: 1.5, scale: 0.0028 },
    tags: ["landscape", "minimal"],
  },
  {
    id: "fluid-venetian",
    name: "Venetian Marble",
    category: "Fluid & Marble",
    categoryTag: "generative",
    volume: "Vol. 05",
    generatorId: "marble-fluid",
    palette: ["#120D0A", "#4A3225", "#A87B58", "#E8D5C4"],
    mode: "dark",
    seed: "venetianmarble",
    params: { swirlIntensity: 1.6, veinContrast: 1.8, scale: 0.0032 },
    tags: ["generative", "trending"],
    isTrending: true,
  },
  {
    id: "holographic-mesh-v2",
    name: "Prismatic Mesh II",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 06",
    generatorId: "mesh-gradient",
    palette: ["#0F0C20", "#3B1578", "#8C1D96", "#E84393", "#FF7675"],
    mode: "dark",
    seed: "meshv2",
    params: { pointsCount: 7, blurRadius: 0.65, pointSize: 0.95 },
    tags: ["gradient", "new"],
    isNew: true,
  },
];

export function getArchiveCategories(): ArchiveCategory[] {
  const allCount = ARCHIVE_PRESETS.length;
  const newCount = ARCHIVE_PRESETS.filter(p => p.isNew).length;
  const trendingCount = ARCHIVE_PRESETS.filter(p => p.isTrending).length;

  const categoryCounts = new Map<string, number>();
  for (const p of ARCHIVE_PRESETS) {
    categoryCounts.set(p.categoryTag, (categoryCounts.get(p.categoryTag) ?? 0) + 1);
  }

  const CATEGORY_LABELS: Record<string, string> = {
    botanicals: "Botanicals",
    geometric: "Geometric",
    abstract: "Abstract",
    monochrome: "Monochrome",
    "earth-sand": "Earth & sand",
    "bold-graphic": "Bold & graphic",
    minimal: "Minimal",
    gradient: "Gradient",
    typography: "Typography",
    retro: "Retro",
    dark: "Dark",
    pastel: "Pastel",
    seasonal: "Seasonal",
    cyberpunk: "Cyberpunk",
    cinematic: "Cinematic",
    brutalism: "Brutalism",
    ethereal: "Ethereal",
    generative: "Generative",
    cosmic: "Cosmic",
    landscape: "Landscape",
    print: "Print",
  };

  const dynamicCategories: ArchiveCategory[] = Array.from(categoryCounts.entries())
    .filter(([, count]) => count > 0)
    .map(([tag, count]) => ({
      id: tag,
      label: CATEGORY_LABELS[tag] ?? tag,
      count,
    }))
    .sort((a, b) => b.count - a.count);

  return [
    { id: "all", label: "All prints", count: allCount },
    { id: "new", label: "New arrivals", count: newCount },
    { id: "trending", label: "Trending", count: trendingCount },
    ...dynamicCategories,
  ].filter(c => c.count > 0);
}

export const ARCHIVE_CATEGORIES: ArchiveCategory[] = getArchiveCategories();
