export type SwatchRecipe = {
  id: string;
  name: string;
  category: string;
  categoryTag: string;
  volume: string;
  generatorId: "waveform" | "fluid-gradient" | "geometric" | "typography";
  palette: string[];
  mode: "light" | "dark" | "auto";
  seed: string;
  params: Record<string, unknown>;
  tags: string[];
  isNew?: boolean;
  isTrending?: boolean;
};

export type ArchiveCategory = {
  id: string;
  label: string;
  count: number;
};

export const ARCHIVE_PRESETS: SwatchRecipe[] = [
  // ─── Botanicals (8 items) ──────────────────────────────────────────────────
  {
    id: "terracotta-bloom",
    name: "Terracotta Bloom",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#8A9A6E", "#E4DCC8", "#4B5A3E", "#2B2A26"],
    mode: "dark",
    seed: "bloom99",
    params: { layers: 6, jaggedness: 0.35, smoothing: 0.75, lineThickness: 2, amplitude: 0.65, fillBelow: true },
    tags: ["botanicals", "new"],
    isNew: true,
  },
  {
    id: "indigo-garden",
    name: "Indigo Garden",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 06",
    generatorId: "fluid-gradient",
    palette: ["#FAF8F4", "#1F3A5F", "#3E6E9E", "#101820"],
    mode: "dark",
    seed: "indigo77",
    params: { blobCount: 5, distortion: 0.4, swirl: 0.7, contrast: 1.2, saturation: 1.1 },
    tags: ["botanicals", "new"],
    isNew: true,
  },
  {
    id: "olive-branch",
    name: "Olive Branch",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 01",
    generatorId: "waveform",
    palette: ["#DAD4C4", "#8A9A72", "#5C6E4E", "#37402C"],
    mode: "light",
    seed: "olive05",
    params: { layers: 4, jaggedness: 0.25, smoothing: 0.85, lineThickness: 2.5, amplitude: 0.7, fillBelow: true },
    tags: ["botanicals"],
  },
  {
    id: "midnight-flora",
    name: "Midnight Flora",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 07",
    generatorId: "typography",
    palette: ["#101820", "#C9552F", "#8A9A6E", "#E4DCC8"],
    mode: "dark",
    seed: "flora99",
    params: { text: "WallMyDevice", font: "Fraunces", size: 0.35, weight: 500, letterSpacing: 2, alignment: "center" },
    tags: ["botanicals", "trending"],
    isTrending: true,
  },
  {
    id: "forest-depth",
    name: "Forest Depth",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 08",
    generatorId: "fluid-gradient",
    palette: ["#1A2B1A", "#3A5E3A", "#7A9E72", "#DAD4C4"],
    mode: "dark",
    seed: "forest11",
    params: { blobCount: 6, distortion: 0.3, swirl: 0.5, contrast: 1.15, saturation: 0.85 },
    tags: ["botanicals"],
  },
  {
    id: "fern-shadow",
    name: "Fern Shadow",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 09",
    generatorId: "waveform",
    palette: ["#2C3B28", "#5C7A50", "#A8C490", "#EDE8DC"],
    mode: "dark",
    seed: "fern22",
    params: { layers: 8, jaggedness: 0.2, smoothing: 0.88, lineThickness: 1.5, amplitude: 0.55, fillBelow: true },
    tags: ["botanicals", "new"],
    isNew: true,
  },
  {
    id: "sage-smoke",
    name: "Sage Smoke",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 10",
    generatorId: "fluid-gradient",
    palette: ["#E2DDD4", "#A0A882", "#627058", "#2E3328"],
    mode: "light",
    seed: "sage33",
    params: { blobCount: 4, distortion: 0.45, swirl: 0.6, contrast: 1.05, saturation: 0.78 },
    tags: ["botanicals"],
  },
  {
    id: "moss-tide",
    name: "Moss Tide",
    category: "Botanicals",
    categoryTag: "botanicals",
    volume: "Vol. 11",
    generatorId: "geometric",
    palette: ["#38472E", "#637A52", "#9CB07E", "#F0EBDE"],
    mode: "dark",
    seed: "moss44",
    params: { shape: "circles", gridSize: 10, rotation: 25, strokeWidth: 1.2, density: 0.6, fillMode: "fill" },
    tags: ["botanicals"],
  },

  // ─── Geometric (7 items) ──────────────────────────────────────────────────
  {
    id: "arches-shadows",
    name: "Arches & Shadows",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#DAD4C4", "#6E7A5C", "#3E4A32", "#2B2A26"],
    mode: "light",
    seed: "arch33",
    params: { shape: "squares", gridSize: 10, rotation: 45, strokeWidth: 2, density: 0.65, fillMode: "both" },
    tags: ["geometric"],
  },
  {
    id: "cobalt-fracture",
    name: "Cobalt Fracture",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 01",
    generatorId: "geometric",
    palette: ["#101820", "#1F3A5F", "#3E6E9E", "#D4CDBC"],
    mode: "dark",
    seed: "cobalt88",
    params: { shape: "triangles", gridSize: 18, rotation: 30, strokeWidth: 1, density: 0.8, fillMode: "stroke" },
    tags: ["geometric", "trending"],
    isTrending: true,
  },
  {
    id: "grid-lattice",
    name: "Grid Lattice",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 03",
    generatorId: "geometric",
    palette: ["#F0EBE0", "#2B2A26", "#8A8579", "#C9552F"],
    mode: "light",
    seed: "lattice15",
    params: { shape: "squares", gridSize: 16, rotation: 0, strokeWidth: 1, density: 0.9, fillMode: "stroke" },
    tags: ["geometric", "new"],
    isNew: true,
  },
  {
    id: "hex-field",
    name: "Hex Field",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 04",
    generatorId: "geometric",
    palette: ["#181820", "#2A2A40", "#4A4A80", "#9090C0"],
    mode: "dark",
    seed: "hexfield",
    params: { shape: "circles", gridSize: 12, rotation: 0, strokeWidth: 1.5, density: 0.75, fillMode: "fill" },
    tags: ["geometric"],
  },
  {
    id: "diamond-grid",
    name: "Diamond Grid",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 05",
    generatorId: "geometric",
    palette: ["#FAF8F4", "#C9552F", "#2B2A26", "#E4DFD3"],
    mode: "light",
    seed: "diamond7",
    params: { shape: "squares", gridSize: 14, rotation: 45, strokeWidth: 1.8, density: 0.7, fillMode: "both" },
    tags: ["geometric", "trending"],
    isTrending: true,
  },
  {
    id: "circuit-lines",
    name: "Circuit Lines",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 06",
    generatorId: "geometric",
    palette: ["#0A1A0A", "#1A5C1A", "#2AA02A", "#7AE07A"],
    mode: "dark",
    seed: "circuit9",
    params: { shape: "squares", gridSize: 20, rotation: 0, strokeWidth: 0.8, density: 0.85, fillMode: "stroke" },
    tags: ["geometric"],
  },
  {
    id: "prism-break",
    name: "Prism Break",
    category: "Geometric",
    categoryTag: "geometric",
    volume: "Vol. 07",
    generatorId: "geometric",
    palette: ["#101025", "#302060", "#6040C0", "#C080FF"],
    mode: "dark",
    seed: "prism77",
    params: { shape: "triangles", gridSize: 16, rotation: 60, strokeWidth: 1.2, density: 0.72, fillMode: "fill" },
    tags: ["geometric", "new"],
    isNew: true,
  },

  // ─── Abstract (6 items) ───────────────────────────────────────────────────
  {
    id: "sagebrush-lines",
    name: "Sagebrush Lines",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 03",
    generatorId: "waveform",
    palette: ["#DAD4C4", "#8A9A72", "#5C6E4E", "#37402C"],
    mode: "light",
    seed: "sage88",
    params: { layers: 8, jaggedness: 0.15, smoothing: 0.9, lineThickness: 1.2, amplitude: 0.5, fillBelow: false },
    tags: ["abstract", "earth-sand"],
  },
  {
    id: "blush-terrain",
    name: "Blush Terrain",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#F3DDD1", "#C9552F", "#5A2411", "#FAF8F4"],
    mode: "light",
    seed: "blush12",
    params: { blobCount: 3, distortion: 0.7, swirl: 0.3, contrast: 0.95, saturation: 1.05 },
    tags: ["abstract", "new"],
    isNew: true,
  },
  {
    id: "aurora-wave",
    name: "Aurora Wave",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 08",
    generatorId: "waveform",
    palette: ["#0D1B2A", "#00B4D8", "#48CAE4", "#90E0EF"],
    mode: "dark",
    seed: "aurora12",
    params: { layers: 10, jaggedness: 0.2, smoothing: 0.92, lineThickness: 1.8, amplitude: 0.6, fillBelow: false },
    tags: ["abstract"],
  },
  {
    id: "oil-slick",
    name: "Oil Slick",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 09",
    generatorId: "fluid-gradient",
    palette: ["#1A1025", "#4A1055", "#8A3080", "#D880D8"],
    mode: "dark",
    seed: "oilslick",
    params: { blobCount: 5, distortion: 0.85, swirl: 0.7, contrast: 1.25, saturation: 1.3 },
    tags: ["abstract"],
  },
  {
    id: "static-noise",
    name: "Static Noise",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 10",
    generatorId: "waveform",
    palette: ["#1A1A1A", "#444444", "#888888", "#CCCCCC"],
    mode: "dark",
    seed: "static66",
    params: { layers: 12, jaggedness: 0.8, smoothing: 0.3, lineThickness: 0.8, amplitude: 0.4, fillBelow: false },
    tags: ["abstract", "monochrome"],
  },
  {
    id: "nebula-drift",
    name: "Nebula Drift",
    category: "Abstract",
    categoryTag: "abstract",
    volume: "Vol. 11",
    generatorId: "fluid-gradient",
    palette: ["#050510", "#1A0A30", "#3A1A60", "#8040C0"],
    mode: "dark",
    seed: "nebula33",
    params: { blobCount: 6, distortion: 0.6, swirl: 0.9, contrast: 1.4, saturation: 1.5 },
    tags: ["abstract", "dark"],
  },

  // ─── Monochrome (5 items) ─────────────────────────────────────────────────
  {
    id: "inkleaf",
    name: "Inkleaf",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 01",
    generatorId: "geometric",
    palette: ["#FAF8F4", "#5B584F", "#2B2A26", "#8A8579"],
    mode: "dark",
    seed: "inkleaf01",
    params: { shape: "circles", gridSize: 12, rotation: 15, strokeWidth: 1.5, density: 0.7, fillMode: "fill" },
    tags: ["monochrome", "trending"],
    isTrending: true,
  },
  {
    id: "monochrome-grid",
    name: "Monochrome Grid",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#09090b", "#27272a", "#a1a1aa", "#fafafa"],
    mode: "dark",
    seed: "monogrid",
    params: { shape: "squares", gridSize: 14, rotation: 0, strokeWidth: 1.2, density: 0.75, fillMode: "fill" },
    tags: ["monochrome"],
  },
  {
    id: "type-specimen",
    name: "Type Specimen",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 03",
    generatorId: "typography",
    palette: ["#FAF8F4", "#2B2A26", "#8A8579"],
    mode: "light",
    seed: "typespec",
    params: { text: "SWATCH", font: "Inter", size: 0.45, weight: 700, letterSpacing: 4, alignment: "center" },
    tags: ["monochrome", "new"],
    isNew: true,
  },
  {
    id: "graphite-flow",
    name: "Graphite Flow",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#1A1A1A", "#404040", "#808080", "#D0D0D0"],
    mode: "dark",
    seed: "graphite5",
    params: { layers: 9, jaggedness: 0.3, smoothing: 0.8, lineThickness: 1.5, amplitude: 0.6, fillBelow: true },
    tags: ["monochrome"],
  },
  {
    id: "ink-wash",
    name: "Ink Wash",
    category: "Monochrome",
    categoryTag: "monochrome",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#FAFAFA", "#E0E0E0", "#A0A0A0", "#404040"],
    mode: "light",
    seed: "inkwash8",
    params: { blobCount: 4, distortion: 0.5, swirl: 0.4, contrast: 0.9, saturation: 0.0 },
    tags: ["monochrome"],
  },

  // ─── Earth & sand (5 items) ───────────────────────────────────────────────
  {
    id: "dune-flow",
    name: "Dune Flow",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#E4DCC8", "#C79A66", "#8A8579", "#2F4A5C"],
    mode: "light",
    seed: "dune42",
    params: { blobCount: 4, distortion: 0.6, swirl: 0.45, contrast: 1.1, saturation: 0.9 },
    tags: ["earth-sand", "trending"],
    isTrending: true,
  },
  {
    id: "horizon-weave",
    name: "Horizon Weave",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 03",
    generatorId: "waveform",
    palette: ["#E4DCC8", "#C79A66", "#4B5A6E", "#2F4A5C"],
    mode: "dark",
    seed: "horizon10",
    params: { layers: 7, jaggedness: 0.45, smoothing: 0.6, lineThickness: 1.8, amplitude: 0.55, fillBelow: true },
    tags: ["earth-sand", "trending"],
    isTrending: true,
  },
  {
    id: "desert-rift",
    name: "Desert Rift",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 04",
    generatorId: "waveform",
    palette: ["#C4A882", "#8C6E50", "#5A4030", "#2E2018"],
    mode: "dark",
    seed: "desert22",
    params: { layers: 6, jaggedness: 0.5, smoothing: 0.65, lineThickness: 2, amplitude: 0.75, fillBelow: true },
    tags: ["earth-sand"],
  },
  {
    id: "ochre-field",
    name: "Ochre Field",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#F0E4CC", "#D4A850", "#8A6832", "#3C2810"],
    mode: "light",
    seed: "ochre55",
    params: { blobCount: 4, distortion: 0.4, swirl: 0.35, contrast: 1.0, saturation: 0.95 },
    tags: ["earth-sand", "new"],
    isNew: true,
  },
  {
    id: "clay-plates",
    name: "Clay Plates",
    category: "Earth & sand",
    categoryTag: "earth-sand",
    volume: "Vol. 06",
    generatorId: "geometric",
    palette: ["#E8D5BE", "#C8A87A", "#8A6840", "#4A3018"],
    mode: "light",
    seed: "clay77",
    params: { shape: "squares", gridSize: 8, rotation: 5, strokeWidth: 2.5, density: 0.55, fillMode: "fill" },
    tags: ["earth-sand"],
  },

  // ─── Bold & graphic (5 items) ─────────────────────────────────────────────
  {
    id: "ember-field",
    name: "Ember Field",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#5A2411", "#C9552F", "#F0B27A", "#2B2A26"],
    mode: "dark",
    seed: "ember55",
    params: { blobCount: 4, distortion: 0.8, swirl: 0.6, contrast: 1.3, saturation: 1.2 },
    tags: ["bold-graphic", "new"],
    isNew: true,
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#1A0500", "#FF4400", "#FF9900", "#FFD700"],
    mode: "dark",
    seed: "solar44",
    params: { blobCount: 5, distortion: 0.9, swirl: 0.7, contrast: 1.5, saturation: 1.6 },
    tags: ["bold-graphic", "trending"],
    isTrending: true,
  },
  {
    id: "neon-grid",
    name: "Neon Grid",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 05",
    generatorId: "geometric",
    palette: ["#050510", "#FF0080", "#00FFCC", "#8800FF"],
    mode: "dark",
    seed: "neongrid",
    params: { shape: "squares", gridSize: 22, rotation: 0, strokeWidth: 0.8, density: 0.9, fillMode: "stroke" },
    tags: ["bold-graphic"],
  },
  {
    id: "acid-wash",
    name: "Acid Wash",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 06",
    generatorId: "fluid-gradient",
    palette: ["#00FF00", "#FFFF00", "#FF0000", "#0000FF"],
    mode: "dark",
    seed: "acid88",
    params: { blobCount: 6, distortion: 0.95, swirl: 0.8, contrast: 1.6, saturation: 2.0 },
    tags: ["bold-graphic", "new"],
    isNew: true,
  },
  {
    id: "blood-orange",
    name: "Blood Orange",
    category: "Bold & graphic",
    categoryTag: "bold-graphic",
    volume: "Vol. 07",
    generatorId: "waveform",
    palette: ["#1A0800", "#C83000", "#FF5520", "#FFCC00"],
    mode: "dark",
    seed: "orange99",
    params: { layers: 5, jaggedness: 0.6, smoothing: 0.5, lineThickness: 3, amplitude: 0.8, fillBelow: true },
    tags: ["bold-graphic"],
  },

  // ─── Minimal (5 items) ────────────────────────────────────────────────────
  {
    id: "paper-field",
    name: "Paper Field",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 01",
    generatorId: "waveform",
    palette: ["#F8F5F0", "#E8E0D5", "#C8BFB0", "#A09888"],
    mode: "light",
    seed: "paper11",
    params: { layers: 3, jaggedness: 0.1, smoothing: 0.95, lineThickness: 0.8, amplitude: 0.3, fillBelow: false },
    tags: ["minimal"],
  },
  {
    id: "linen-wave",
    name: "Linen Wave",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 02",
    generatorId: "waveform",
    palette: ["#EDE8E0", "#D8D0C4", "#C0B8A8", "#888070"],
    mode: "light",
    seed: "linen22",
    params: { layers: 4, jaggedness: 0.08, smoothing: 0.97, lineThickness: 1, amplitude: 0.25, fillBelow: false },
    tags: ["minimal", "new"],
    isNew: true,
  },
  {
    id: "dust-circle",
    name: "Dust Circle",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 03",
    generatorId: "geometric",
    palette: ["#F5F0E8", "#D0C8B8", "#A09888", "#706858"],
    mode: "light",
    seed: "dust33",
    params: { shape: "circles", gridSize: 6, rotation: 0, strokeWidth: 0.7, density: 0.4, fillMode: "stroke" },
    tags: ["minimal"],
  },
  {
    id: "fog-gradient",
    name: "Fog Gradient",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#FAFAF8", "#E8E8E5", "#D0D0CC", "#B0B0AC"],
    mode: "light",
    seed: "fog44",
    params: { blobCount: 3, distortion: 0.2, swirl: 0.15, contrast: 0.85, saturation: 0.1 },
    tags: ["minimal"],
  },
  {
    id: "rice-paper",
    name: "Rice Paper",
    category: "Minimal",
    categoryTag: "minimal",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#F8F4EC", "#EDE4D4", "#D8CCC0", "#C0B4A8"],
    mode: "light",
    seed: "rice55",
    params: { blobCount: 2, distortion: 0.15, swirl: 0.1, contrast: 0.8, saturation: 0.05 },
    tags: ["minimal", "trending"],
    isTrending: true,
  },

  // ─── Gradient (5 items) ───────────────────────────────────────────────────
  {
    id: "sunset-pour",
    name: "Sunset Pour",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#FF6B35", "#F7C59F", "#EFEFD0", "#004E89"],
    mode: "light",
    seed: "sunset1",
    params: { blobCount: 4, distortion: 0.5, swirl: 0.55, contrast: 1.15, saturation: 1.2 },
    tags: ["gradient", "new"],
    isNew: true,
  },
  {
    id: "ocean-bloom",
    name: "Ocean Bloom",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#03045E", "#0077B6", "#00B4D8", "#90E0EF"],
    mode: "dark",
    seed: "ocean22",
    params: { blobCount: 5, distortion: 0.4, swirl: 0.65, contrast: 1.2, saturation: 1.1 },
    tags: ["gradient", "trending"],
    isTrending: true,
  },
  {
    id: "aurora-boreal",
    name: "Aurora Borealis",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#011627", "#00CFCF", "#00FF87", "#7B2FBE"],
    mode: "dark",
    seed: "aurora3",
    params: { blobCount: 6, distortion: 0.6, swirl: 0.8, contrast: 1.35, saturation: 1.4 },
    tags: ["gradient"],
  },
  {
    id: "candy-cloud",
    name: "Candy Cloud",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#FFE5F0", "#FFB3D1", "#FF80B5", "#FF4D9B"],
    mode: "light",
    seed: "candy44",
    params: { blobCount: 4, distortion: 0.35, swirl: 0.5, contrast: 1.0, saturation: 1.2 },
    tags: ["gradient", "pastel"],
  },
  {
    id: "violet-dusk",
    name: "Violet Dusk",
    category: "Gradient",
    categoryTag: "gradient",
    volume: "Vol. 05",
    generatorId: "fluid-gradient",
    palette: ["#1A0533", "#5C1A7A", "#A044C0", "#E8A0FF"],
    mode: "dark",
    seed: "violet5",
    params: { blobCount: 5, distortion: 0.55, swirl: 0.7, contrast: 1.3, saturation: 1.3 },
    tags: ["gradient"],
  },

  // ─── Typography (5 items) ─────────────────────────────────────────────────
  {
    id: "editorial-bold",
    name: "Editorial Bold",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 01",
    generatorId: "typography",
    palette: ["#101820", "#D4CDBC", "#C9552F", "#8A8579"],
    mode: "dark",
    seed: "editorial",
    params: { text: "TYPE", font: "Fraunces", size: 0.7, weight: 900, letterSpacing: 8, alignment: "center" },
    tags: ["typography", "trending"],
    isTrending: true,
  },
  {
    id: "mono-whisper",
    name: "Mono Whisper",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 02",
    generatorId: "typography",
    palette: ["#FAF8F4", "#2B2A26", "#8A8579", "#C9552F"],
    mode: "light",
    seed: "whisper2",
    params: { text: "WALL", font: "Inter", size: 0.5, weight: 300, letterSpacing: 16, alignment: "center" },
    tags: ["typography", "minimal"],
  },
  {
    id: "serif-study",
    name: "Serif Study",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 03",
    generatorId: "typography",
    palette: ["#F5F0E8", "#1A1A18", "#6A6458", "#C9552F"],
    mode: "light",
    seed: "serif33",
    params: { text: "DESIGN", font: "Fraunces", size: 0.4, weight: 700, letterSpacing: 3, alignment: "left" },
    tags: ["typography"],
  },
  {
    id: "code-poetic",
    name: "Code Poetic",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 04",
    generatorId: "typography",
    palette: ["#0A0F0A", "#00FF41", "#00AA2C", "#004D14"],
    mode: "dark",
    seed: "code44",
    params: { text: "01010101", font: "Inter", size: 0.35, weight: 700, letterSpacing: 6, alignment: "center" },
    tags: ["typography"],
  },
  {
    id: "blueprint-text",
    name: "Blueprint Text",
    category: "Typography",
    categoryTag: "typography",
    volume: "Vol. 05",
    generatorId: "typography",
    palette: ["#0A1A3A", "#1A4080", "#4080C0", "#C0E0FF"],
    mode: "dark",
    seed: "blueprint",
    params: { text: "STRUCTURE", font: "Inter", size: 0.32, weight: 400, letterSpacing: 10, alignment: "center" },
    tags: ["typography", "new"],
    isNew: true,
  },

  // ─── Retro (5 items) ──────────────────────────────────────────────────────
  {
    id: "vhs-noise",
    name: "VHS Noise",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 01",
    generatorId: "waveform",
    palette: ["#180020", "#600060", "#C000C0", "#FF80FF"],
    mode: "dark",
    seed: "vhs11",
    params: { layers: 15, jaggedness: 0.9, smoothing: 0.2, lineThickness: 0.6, amplitude: 0.35, fillBelow: false },
    tags: ["retro"],
  },
  {
    id: "vapor-grid",
    name: "Vapor Grid",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#0D0D2B", "#FF2D78", "#00FFFF", "#FF9A00"],
    mode: "dark",
    seed: "vapor22",
    params: { shape: "squares", gridSize: 18, rotation: 15, strokeWidth: 1, density: 0.8, fillMode: "stroke" },
    tags: ["retro", "trending"],
    isTrending: true,
  },
  {
    id: "lofi-sunset",
    name: "Lo-Fi Sunset",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#FFB347", "#FF6B6B", "#A855F7", "#6366F1"],
    mode: "light",
    seed: "lofi33",
    params: { blobCount: 4, distortion: 0.35, swirl: 0.4, contrast: 1.1, saturation: 0.9 },
    tags: ["retro", "new"],
    isNew: true,
  },
  {
    id: "pixel-garden",
    name: "Pixel Garden",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 04",
    generatorId: "geometric",
    palette: ["#AADDAA", "#448844", "#224422", "#88CC88"],
    mode: "light",
    seed: "pixel44",
    params: { shape: "squares", gridSize: 24, rotation: 0, strokeWidth: 0, density: 1, fillMode: "fill" },
    tags: ["retro"],
  },
  {
    id: "crt-glow",
    name: "CRT Glow",
    category: "Retro",
    categoryTag: "retro",
    volume: "Vol. 05",
    generatorId: "waveform",
    palette: ["#050505", "#003300", "#00AA00", "#00FF44"],
    mode: "dark",
    seed: "crt55",
    params: { layers: 8, jaggedness: 0.6, smoothing: 0.45, lineThickness: 1.2, amplitude: 0.5, fillBelow: false },
    tags: ["retro"],
  },

  // ─── Dark (5 items) ───────────────────────────────────────────────────────
  {
    id: "abyss",
    name: "Abyss",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#000000", "#0A0A0A", "#141414", "#1E1E1E"],
    mode: "dark",
    seed: "abyss11",
    params: { blobCount: 3, distortion: 0.7, swirl: 0.5, contrast: 1.0, saturation: 0.0 },
    tags: ["dark", "monochrome"],
  },
  {
    id: "void-matter",
    name: "Void Matter",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 02",
    generatorId: "geometric",
    palette: ["#050508", "#101018", "#202030", "#303050"],
    mode: "dark",
    seed: "void22",
    params: { shape: "circles", gridSize: 16, rotation: 0, strokeWidth: 0.5, density: 0.5, fillMode: "fill" },
    tags: ["dark"],
  },
  {
    id: "carbon-waves",
    name: "Carbon Waves",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 03",
    generatorId: "waveform",
    palette: ["#0A0A0A", "#1A1A1A", "#2A2A2A", "#3A3A3A"],
    mode: "dark",
    seed: "carbon3",
    params: { layers: 8, jaggedness: 0.25, smoothing: 0.85, lineThickness: 1.5, amplitude: 0.5, fillBelow: true },
    tags: ["dark"],
  },
  {
    id: "nightfall",
    name: "Nightfall",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#000010", "#050520", "#0A0A40", "#101060"],
    mode: "dark",
    seed: "night44",
    params: { blobCount: 4, distortion: 0.4, swirl: 0.6, contrast: 1.1, saturation: 0.8 },
    tags: ["dark", "new"],
    isNew: true,
  },
  {
    id: "obsidian-flow",
    name: "Obsidian Flow",
    category: "Dark",
    categoryTag: "dark",
    volume: "Vol. 05",
    generatorId: "waveform",
    palette: ["#020202", "#0D0D10", "#181820", "#252530"],
    mode: "dark",
    seed: "obsidian",
    params: { layers: 10, jaggedness: 0.3, smoothing: 0.9, lineThickness: 1, amplitude: 0.4, fillBelow: true },
    tags: ["dark", "minimal"],
  },

  // ─── Pastel (5 items) ─────────────────────────────────────────────────────
  {
    id: "cotton-sky",
    name: "Cotton Sky",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 01",
    generatorId: "fluid-gradient",
    palette: ["#E8F4FD", "#B3D9F5", "#8EC8F0", "#64B5E8"],
    mode: "light",
    seed: "cotton1",
    params: { blobCount: 4, distortion: 0.3, swirl: 0.4, contrast: 0.95, saturation: 0.7 },
    tags: ["pastel", "new"],
    isNew: true,
  },
  {
    id: "blush-petal",
    name: "Blush Petal",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 02",
    generatorId: "fluid-gradient",
    palette: ["#FFF0F0", "#FFD0D5", "#FFB0C0", "#FF90A8"],
    mode: "light",
    seed: "blush22",
    params: { blobCount: 4, distortion: 0.25, swirl: 0.35, contrast: 0.9, saturation: 0.75 },
    tags: ["pastel", "trending"],
    isTrending: true,
  },
  {
    id: "mint-cool",
    name: "Mint Cool",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 03",
    generatorId: "fluid-gradient",
    palette: ["#E8FFF5", "#B0EEDD", "#78DCC5", "#48C8A8"],
    mode: "light",
    seed: "mint33",
    params: { blobCount: 3, distortion: 0.3, swirl: 0.45, contrast: 0.92, saturation: 0.72 },
    tags: ["pastel"],
  },
  {
    id: "lavender-haze",
    name: "Lavender Haze",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 04",
    generatorId: "fluid-gradient",
    palette: ["#F5F0FF", "#DDD0F5", "#C0A8E8", "#A080D8"],
    mode: "light",
    seed: "lavender",
    params: { blobCount: 4, distortion: 0.28, swirl: 0.38, contrast: 0.88, saturation: 0.68 },
    tags: ["pastel"],
  },
  {
    id: "peach-soft",
    name: "Peach Soft",
    category: "Pastel",
    categoryTag: "pastel",
    volume: "Vol. 05",
    generatorId: "waveform",
    palette: ["#FFF5F0", "#FFD8C8", "#FFB898", "#FF9870"],
    mode: "light",
    seed: "peach55",
    params: { layers: 5, jaggedness: 0.12, smoothing: 0.92, lineThickness: 1.2, amplitude: 0.35, fillBelow: false },
    tags: ["pastel"],
  },
];

export function getArchiveCategories(): ArchiveCategory[] {
  const allCount = ARCHIVE_PRESETS.length;
  const newCount = ARCHIVE_PRESETS.filter(p => p.isNew).length;
  const trendingCount = ARCHIVE_PRESETS.filter(p => p.isTrending).length;

  const categoryCounts = new Map<string, number>();
  for (const p of ARCHIVE_PRESETS) {
    categoryCounts.set(p.categoryTag, (categoryCounts.get(p.categoryTag) ?? 0) + 1);
  }

  const CATEGORY_LABELS: Record<string, string> = {
    botanicals: "Botanicals",
    geometric: "Geometric",
    abstract: "Abstract",
    monochrome: "Monochrome",
    "earth-sand": "Earth & sand",
    "bold-graphic": "Bold & graphic",
    minimal: "Minimal",
    gradient: "Gradient",
    typography: "Typography",
    retro: "Retro",
    dark: "Dark",
    pastel: "Pastel",
  };

  const dynamicCategories: ArchiveCategory[] = Array.from(categoryCounts.entries())
    .filter(([, count]) => count > 0)
    .map(([tag, count]) => ({
      id: tag,
      label: CATEGORY_LABELS[tag] ?? tag,
      count,
    }))
    .sort((a, b) => b.count - a.count);

  return [
    { id: "all", label: "All prints", count: allCount },
    { id: "new", label: "New arrivals", count: newCount },
    { id: "trending", label: "Trending", count: trendingCount },
    ...dynamicCategories,
  ].filter(c => c.count > 0);
}

export const ARCHIVE_CATEGORIES: ArchiveCategory[] = getArchiveCategories();
